export interface EnglishExampleSentence {
    wordId: string;
    english: string;
}

/**
 * Fixed starter examples for the vocabulary cards.
 *
 * This catalog is intentionally separate from the optional listening catalog:
 * a card can show a sentence without making that sentence eligible for the
 * listening offer or changing any learning progression.
 */
const examples: readonly EnglishExampleSentence[] = [
    // Level 1 · food
    { wordId: 'apple', english: 'This is an apple.' },
    { wordId: 'orange', english: 'This is an orange.' },
    { wordId: 'banana', english: 'This is a banana.' },
    { wordId: 'egg', english: 'This is an egg.' },
    { wordId: 'milk', english: 'I drink milk.' },
    { wordId: 'bread', english: 'I eat bread.' },
    { wordId: 'rice', english: 'I eat rice.' },
    { wordId: 'meat', english: 'I like meat.' },
    { wordId: 'water', english: 'I drink water.' },
    { wordId: 'juice', english: 'I drink juice.' },
    { wordId: 'cake', english: 'I like cake.' },
    { wordId: 'pizza', english: 'I like pizza.' },
    { wordId: 'candy', english: 'This candy is sweet.' },
    { wordId: 'vegetable', english: 'I eat a vegetable.' },
    { wordId: 'fruit', english: 'I like fruit.' },

    // Level 1 · animals
    { wordId: 'dog', english: 'This is a dog.' },
    { wordId: 'cat', english: 'Look at the cat.' },
    { wordId: 'bird', english: 'The bird can fly.' },
    { wordId: 'fish', english: 'The fish can swim.' },
    { wordId: 'rabbit', english: 'The rabbit is fast.' },
    { wordId: 'elephant', english: 'The elephant is big.' },
    { wordId: 'lion', english: 'The lion is strong.' },
    { wordId: 'tiger', english: 'The tiger can run.' },
    { wordId: 'monkey', english: 'The monkey can jump.' },
    { wordId: 'bear', english: 'The bear is big.' },
    { wordId: 'horse', english: 'The horse can run.' },
    { wordId: 'cow', english: 'The cow eats grass.' },
    { wordId: 'pig', english: 'The pig is pink.' },
    { wordId: 'mouse', english: 'The mouse is small.' },
    { wordId: 'sheep', english: 'The sheep has wool.' },

    // Level 1 · numbers
    { wordId: 'one', english: 'I have one apple.' },
    { wordId: 'two', english: 'I have two apples.' },
    { wordId: 'three', english: 'I have three apples.' },
    { wordId: 'four', english: 'I see four birds.' },
    { wordId: 'five', english: 'I see five stars.' },
    { wordId: 'six', english: 'I see six fish.' },
    { wordId: 'seven', english: 'I see seven flowers.' },
    { wordId: 'eight', english: 'I see eight balls.' },
    { wordId: 'nine', english: 'I see nine books.' },
    { wordId: 'ten', english: 'I can count to ten.' },
    { wordId: 'hundred', english: 'One hundred is a big number.' },
    { wordId: 'thousand', english: 'One thousand is a big number.' },

    // Level 1 · everyday words
    { wordId: 'yes', english: 'Yes, I can.' },
    { wordId: 'no', english: 'No, thank you.' },
    { wordId: 'hello', english: 'Hello, my friend.' },
    { wordId: 'goodbye', english: 'Goodbye, see you.' },
    { wordId: 'please', english: 'Please help me.' },
    { wordId: 'thank', english: 'Thank you very much.' },

    // Level 1 · adjectives
    { wordId: 'good', english: 'This apple is good.' },
    { wordId: 'bad', english: 'This candy is bad.' },
    { wordId: 'big', english: 'The elephant is big.' },
    { wordId: 'small', english: 'The mouse is small.' },
    { wordId: 'new', english: 'This is a new book.' },
    { wordId: 'old', english: 'This is an old tree.' },
    { wordId: 'hot', english: 'The soup is hot.' },
    { wordId: 'cold', english: 'The water is cold.' },
    { wordId: 'happy', english: 'I am happy today.' },
    { wordId: 'sad', english: 'The song is sad.' },

    // Level 1 · verbs
    { wordId: 'like', english: 'I like apples.' },
    { wordId: 'want', english: 'I want some juice.' },

    // Level 2 · body
    { wordId: 'head', english: 'This is my head.' },
    { wordId: 'face', english: 'Wash your face.' },
    { wordId: 'eye', english: 'I see with one eye.' },
    { wordId: 'ear', english: 'My ear can hear.' },
    { wordId: 'nose', english: 'Touch your nose.' },
    { wordId: 'mouth', english: 'Open your mouth.' },
    { wordId: 'hand', english: 'Hold my hand.' },
    { wordId: 'arm', english: 'Raise your arm.' },
    { wordId: 'leg', english: 'My leg is strong.' },
    { wordId: 'foot', english: 'My foot is small.' },
    { wordId: 'hair', english: 'Her hair is long.' },
    { wordId: 'finger', english: 'Point with one finger.' },
    { wordId: 'tooth', english: 'Brush one tooth.' },
    { wordId: 'neck', english: 'My neck is warm.' },
    { wordId: 'shoulder', english: 'Touch your shoulder.' },

    // Level 2 · family
    { wordId: 'father', english: 'My father is kind.' },
    { wordId: 'mother', english: 'My mother is kind.' },
    { wordId: 'brother', english: 'My brother can run.' },
    { wordId: 'sister', english: 'My sister can read.' },
    { wordId: 'family', english: 'I love my family.' },
    { wordId: 'baby', english: 'The baby is small.' },
    { wordId: 'parent', english: 'Ask your parent.' },
    { wordId: 'son', english: 'Their son can run.' },
    { wordId: 'daughter', english: 'Her daughter is happy.' },
    { wordId: 'grandfather', english: 'My grandfather tells stories.' },
    { wordId: 'grandmother', english: 'My grandmother is kind.' },

    // Level 2 · colors
    { wordId: 'red', english: 'The apple is red.' },
    { wordId: 'blue', english: 'The sky is blue.' },
    { wordId: 'green', english: 'The tree is green.' },
    { wordId: 'yellow', english: 'The flower is yellow.' },
    { wordId: 'white', english: 'The snow is white.' },
    { wordId: 'black', english: 'The cat is black.' },
    { wordId: 'pink', english: 'The pig is pink.' },
    { wordId: 'brown', english: 'The bear is brown.' },
    { wordId: 'purple', english: 'This flower is purple.' },
    { wordId: 'gray', english: 'The mouse is gray.' },
    { wordId: 'orange_lv2', english: 'The ball is orange.' },

    // Level 2 · people
    { wordId: 'boy', english: 'The boy can run.' },
    { wordId: 'girl', english: 'The girl can read.' },
    { wordId: 'man', english: 'The man is tall.' },
    { wordId: 'woman', english: 'The woman is kind.' },
    { wordId: 'child', english: 'The child can play.' },
    { wordId: 'friend', english: 'My friend is happy.' },
    { wordId: 'teacher', english: 'My teacher can help.' },
    { wordId: 'student', english: 'The student can read.' },

    // Level 2 · adjectives
    { wordId: 'long', english: 'The rope is long.' },
    { wordId: 'short', english: 'The pencil is short.' },
    { wordId: 'tall', english: 'The man is tall.' },
    { wordId: 'young', english: 'The child is young.' },
    { wordId: 'large', english: 'The elephant is large.' },
    { wordId: 'little', english: 'The baby is little.' },

    // Level 2 · verbs
    { wordId: 'eat', english: 'I eat an apple.' },
    { wordId: 'drink', english: 'I drink water.' },
    { wordId: 'have', english: 'I have a book.' },
    { wordId: 'see', english: 'I see a bird.' },
    { wordId: 'look', english: 'Look at the flower.' },
    { wordId: 'love', english: 'I love my family.' },
    { wordId: 'know', english: 'I know the answer.' },
    { wordId: 'think', english: 'I think of home.' },

    // Level 3 · places
    { wordId: 'house', english: 'This is my house.' },
    { wordId: 'home', english: 'I am at home.' },
    { wordId: 'room', english: 'This is my room.' },
    { wordId: 'school', english: 'I go to school.' },
    { wordId: 'park', english: 'We play in the park.' },
    { wordId: 'station', english: 'The train is at the station.' },
    { wordId: 'hospital', english: 'The doctor is at the hospital.' },
    { wordId: 'restaurant', english: 'We eat at the restaurant.' },
    { wordId: 'store', english: 'I go to the store.' },
    { wordId: 'library', english: 'I read at the library.' },

    // Level 3 · school
    { wordId: 'class', english: 'This is our class.' },
    { wordId: 'desk', english: 'My book is on the desk.' },
    { wordId: 'chair', english: 'Sit on the chair.' },
    { wordId: 'book', english: 'I read a book.' },
    { wordId: 'pen', english: 'I write with a pen.' },
    { wordId: 'pencil', english: 'I write with a pencil.' },
    { wordId: 'notebook', english: 'This is my notebook.' },
    { wordId: 'homework', english: 'I do my homework.' },
    { wordId: 'test', english: 'I take a test.' },
    { wordId: 'question', english: 'I have a question.' },

    // Level 3 · objects and transport
    { wordId: 'bag', english: 'My book is in the bag.' },
    { wordId: 'box', english: 'The ball is in the box.' },
    { wordId: 'door', english: 'Open the door, please.' },
    { wordId: 'window', english: 'Look out the window.' },
    { wordId: 'clock', english: 'The clock is on the wall.' },
    { wordId: 'phone', english: 'I use my phone.' },
    { wordId: 'car', english: 'I ride in a car.' },
    { wordId: 'bus', english: 'I ride the bus.' },
    { wordId: 'train', english: 'I see a train.' },
    { wordId: 'bike', english: 'I ride my bike.' },

    // Level 3 · verbs
    { wordId: 'go', english: 'I go to school.' },
    { wordId: 'come', english: 'Come to my home.' },
    { wordId: 'run', english: 'I can run fast.' },
    { wordId: 'walk', english: 'I walk to school.' },
    { wordId: 'stop', english: 'Please stop at the door.' },
    { wordId: 'sit', english: 'I sit on a chair.' },
    { wordId: 'stand', english: 'I stand by the door.' },
    { wordId: 'sleep', english: 'I sleep at home.' },
    { wordId: 'wake', english: 'I wake up early.' },
    { wordId: 'get', english: 'I get a new book.' },
    { wordId: 'put', english: 'Put the pen in the bag.' },
    { wordId: 'take', english: 'I take a bus.' },
    { wordId: 'give', english: 'I give my friend a book.' },
    { wordId: 'make', english: 'I make a paper plane.' },
    { wordId: 'do', english: 'I do my homework.' },
    { wordId: 'use', english: 'I use a pencil.' },
    { wordId: 'play', english: 'I play in the park.' },
    { wordId: 'work', english: 'I work at school.' },
    { wordId: 'study', english: 'I study at home.' },
    { wordId: 'read', english: 'I read a book.' },
    { wordId: 'write', english: 'I write in my notebook.' },
    { wordId: 'speak', english: 'I speak to my teacher.' },
    { wordId: 'say', english: 'I say hello.' },
    { wordId: 'tell', english: 'I tell my friend.' },
    { wordId: 'ask', english: 'I ask a question.' },
    { wordId: 'answer', english: 'I answer the question.' },
    { wordId: 'listen', english: 'I listen to my teacher.' },
    { wordId: 'watch', english: 'I watch the bird.' },
    { wordId: 'help', english: 'I help my family.' },
    { wordId: 'learn', english: 'I learn at school.' },

    // Level 4 · nature
    { wordId: 'sun', english: 'The sun is bright.' },
    { wordId: 'moon', english: 'The moon is bright.' },
    { wordId: 'star', english: 'I see a star.' },
    { wordId: 'sky', english: 'The sky is blue.' },
    { wordId: 'sea', english: 'The sea is wide.' },
    { wordId: 'mountain', english: 'The mountain is high.' },
    { wordId: 'river', english: 'The river is long.' },
    { wordId: 'tree', english: 'The tree is green.' },
    { wordId: 'flower', english: 'This flower is pretty.' },
    { wordId: 'rain', english: 'I like the rain.' },
    { wordId: 'snow', english: 'The snow is cold.' },
    { wordId: 'wind', english: 'The wind is strong.' },
    { wordId: 'cloud', english: 'A cloud is in the sky.' },
    { wordId: 'fire', english: 'The fire is hot.' },
    { wordId: 'earth', english: 'We live on Earth.' },

    // Level 4 · time
    { wordId: 'day', english: 'This is a sunny day.' },
    { wordId: 'night', english: 'The night is dark.' },
    { wordId: 'morning', english: 'Good morning, my friend.' },
    { wordId: 'afternoon', english: 'Good afternoon, teacher.' },
    { wordId: 'evening', english: 'Good evening, everyone.' },
    { wordId: 'week', english: 'This week is busy.' },
    { wordId: 'month', english: 'This month is long.' },
    { wordId: 'year', english: 'This year is new.' },
    { wordId: 'today', english: 'I am happy today.' },
    { wordId: 'tomorrow', english: 'We can play tomorrow.' },
    { wordId: 'yesterday', english: 'We played yesterday.' },
    { wordId: 'now', english: 'I am ready now.' },
    { wordId: 'time', english: 'I have time to play.' },
    { wordId: 'hour', english: 'One hour is enough.' },
    { wordId: 'minute', english: 'Wait one minute, please.' },

    // Level 4 · verbs
    { wordId: 'open', english: 'Open the window, please.' },
    { wordId: 'close', english: 'Close the door, please.' },
    { wordId: 'turn', english: 'Turn left at the corner.' },
    { wordId: 'move', english: 'Move the chair, please.' },
    { wordId: 'fly', english: 'Birds can fly high.' },
    { wordId: 'swim', english: 'Fish can swim well.' },
    { wordId: 'jump', english: 'I can jump high.' },
    { wordId: 'start', english: 'We start the game now.' },
    { wordId: 'begin', english: 'We begin our lesson.' },
    { wordId: 'finish', english: 'I finish my homework.' },
    { wordId: 'end', english: 'The game will end soon.' },
    { wordId: 'wait', english: 'Please wait for me.' },
    { wordId: 'call', english: 'I call my friend.' },
    { wordId: 'bring', english: 'Bring your book here.' },
    { wordId: 'keep', english: 'Keep your room clean.' },
    { wordId: 'find', english: 'I find my key.' },
    { wordId: 'lose', english: 'I never lose my bag.' },
    { wordId: 'win', english: 'We can win this game.' },
    { wordId: 'try', english: 'I try again.' },
    { wordId: 'feel', english: 'I feel happy today.' },
    { wordId: 'become', english: 'I want to become strong.' },
    { wordId: 'grow', english: 'Plants grow in the sun.' },
    { wordId: 'need', english: 'I need some water.' },
    { wordId: 'hope', english: 'I hope you are well.' },
    { wordId: 'sing', english: 'We sing a song.' },
    { wordId: 'dance', english: 'We dance at the party.' },
    { wordId: 'draw', english: 'I draw a picture.' },
    { wordId: 'show', english: 'Show me your picture.' },
    { wordId: 'meet', english: 'I meet my friend.' },
    { wordId: 'talk', english: 'We talk after class.' },

    // Level 5 · days and months
    { wordId: 'Sunday', english: 'We play on Sunday.' },
    { wordId: 'Monday', english: 'School starts on Monday.' },
    { wordId: 'Tuesday', english: 'I read on Tuesday.' },
    { wordId: 'Wednesday', english: 'We meet on Wednesday.' },
    { wordId: 'Thursday', english: 'I study on Thursday.' },
    { wordId: 'Friday', english: 'Friday is a school day.' },
    { wordId: 'Saturday', english: 'I rest on Saturday.' },
    { wordId: 'January', english: 'January is cold here.' },
    { wordId: 'February', english: 'February is a short month.' },
    { wordId: 'March', english: 'Flowers grow in March.' },
    { wordId: 'April', english: 'Rain falls in April.' },
    { wordId: 'May', english: 'May is warm here.' },
    { wordId: 'June', english: 'Summer starts in June.' },
    { wordId: 'July', english: 'July is hot here.' },
    { wordId: 'August', english: 'We travel in August.' },
    { wordId: 'September', english: 'School starts in September.' },
    { wordId: 'October', english: 'Leaves fall in October.' },
    { wordId: 'November', english: 'November comes after October.' },
    { wordId: 'December', english: 'Christmas comes in December.' },
    { wordId: 'spring', english: 'Flowers grow in spring.' },
    { wordId: 'summer', english: 'We swim in summer.' },
    { wordId: 'fall', english: 'Leaves change in fall.' },
    { wordId: 'winter', english: 'Snow falls in winter.' },

    // Level 5 · adjectives
    { wordId: 'nice', english: 'This is a nice day.' },
    { wordId: 'great', english: 'You did a great job.' },
    { wordId: 'fine', english: 'I feel fine today.' },
    { wordId: 'high', english: 'The mountain is high.' },
    { wordId: 'low', english: 'The chair is low.' },
    { wordId: 'warm', english: 'The soup is warm.' },
    { wordId: 'cool', english: 'The evening is cool.' },
    { wordId: 'fast', english: 'The horse is fast.' },
    { wordId: 'slow', english: 'The turtle is slow.' },
    { wordId: 'easy', english: 'This game is easy.' },
    { wordId: 'difficult', english: 'This question is difficult.' },
    { wordId: 'hard', english: 'This work is hard.' },
    { wordId: 'soft', english: 'The pillow is soft.' },
    { wordId: 'right', english: 'Your answer is right.' },
    { wordId: 'wrong', english: 'That answer is wrong.' },
    { wordId: 'same', english: 'We have the same book.' },
    { wordId: 'different', english: 'This book is different.' },
    { wordId: 'many', english: 'I see many stars.' },
    { wordId: 'much', english: 'I do not have much time.' },
    { wordId: 'some', english: 'I have some candy.' },
    { wordId: 'all', english: 'All the children can play.' },
    { wordId: 'every', english: 'I read every day.' },

    // Level 5 · adverbs and questions
    { wordId: 'very', english: 'This is very nice.' },
    { wordId: 'really', english: 'I really like this song.' },
    { wordId: 'so', english: 'I am so happy.' },
    { wordId: 'too', english: 'This bag is too heavy.' },
    { wordId: 'just', english: 'I just got home.' },
    { wordId: 'only', english: 'I have only one book.' },
    { wordId: 'always', english: 'I always help my family.' },
    { wordId: 'usually', english: 'I usually walk to school.' },
    { wordId: 'often', english: 'I often read at home.' },
    { wordId: 'sometimes', english: 'I sometimes play outside.' },
    { wordId: 'never', english: 'I never lose my key.' },
    { wordId: 'here', english: 'Come and sit here.' },
    { wordId: 'there', english: 'Put the book there.' },
    { wordId: 'what', english: 'I know what you mean.' },
    { wordId: 'who', english: 'I know who she is.' },

    // Level 6 · people and jobs
    { wordId: 'people', english: 'Many people live here.' },
    { wordId: 'person', english: 'That person is kind.' },
    { wordId: 'neighbor', english: 'My neighbor has a dog.' },
    { wordId: 'guest', english: 'Our guest is here.' },
    { wordId: 'king', english: 'The king lives in a castle.' },
    { wordId: 'queen', english: 'The queen wears a crown.' },
    { wordId: 'doctor', english: 'The doctor helps people.' },
    { wordId: 'nurse', english: 'The nurse is kind.' },
    { wordId: 'police', english: 'The police keep us safe.' },
    { wordId: 'driver', english: 'The driver has a car.' },
    { wordId: 'cook', english: 'The cook makes lunch.' },
    { wordId: 'farmer', english: 'The farmer grows food.' },
    { wordId: 'singer', english: 'The singer sings a song.' },
    { wordId: 'player', english: 'The player kicks the ball.' },
    { wordId: 'artist', english: 'The artist draws a picture.' },
    { wordId: 'writer', english: 'The writer writes a story.' },
    { wordId: 'pilot', english: 'The pilot flies a plane.' },
    { wordId: 'scientist', english: 'The scientist does research.' },

    // Level 6 · buildings
    { wordId: 'building', english: 'This building is tall.' },
    { wordId: 'office', english: 'My father works in an office.' },
    { wordId: 'hotel', english: 'We stay at the hotel.' },
    { wordId: 'temple', english: 'The temple is old.' },
    { wordId: 'shrine', english: 'We visit the shrine.' },
    { wordId: 'castle', english: 'The castle is big.' },
    { wordId: 'tower', english: 'The tower is high.' },
    { wordId: 'bridge', english: 'We walk across the bridge.' },
    { wordId: 'church', english: 'The church has a tall tower.' },
    { wordId: 'museum', english: 'We see art at the museum.' },
    { wordId: 'airport', english: 'The plane is at the airport.' },
    { wordId: 'factory', english: 'The factory makes cars.' },

    // Level 6 · meals
    { wordId: 'breakfast', english: 'I eat breakfast at home.' },
    { wordId: 'lunch', english: 'We have lunch at noon.' },
    { wordId: 'dinner', english: 'We eat dinner together.' },
    { wordId: 'meal', english: 'This meal is good.' },
    { wordId: 'dish', english: 'This dish smells nice.' },
    { wordId: 'menu', english: 'I read the menu.' },
    { wordId: 'taste', english: 'The soup has a good taste.' },
    { wordId: 'smell', english: 'I like the smell.' },

    // Level 6 · verbs
    { wordId: 'live', english: 'I live with my family.' },
    { wordId: 'stay', english: 'We stay at home.' },
    { wordId: 'visit', english: 'I visit my grandmother.' },
    { wordId: 'join', english: 'Come and join our game.' },
    { wordId: 'clean', english: 'I clean my room.' },
    { wordId: 'wash', english: 'I wash my hands.' },
    { wordId: 'wear', english: 'I wear a warm coat.' },
    { wordId: 'carry', english: 'I carry my school bag.' },
    { wordId: 'die', english: 'Plants die without water.' },
    { wordId: 'born', english: 'I was born in spring.' },

    // Level 6 · adjectives
    { wordId: 'hungry', english: 'I am hungry now.' },
    { wordId: 'thirsty', english: 'I am thirsty now.' },
    { wordId: 'tired', english: 'I feel tired today.' },
    { wordId: 'angry', english: 'The boy is angry.' },
    { wordId: 'glad', english: 'I am glad to see you.' },
    { wordId: 'sorry', english: 'I am sorry, my friend.' },
    { wordId: 'true', english: 'This story is true.' },
    { wordId: 'important', english: 'Family is important to me.' },
    { wordId: 'famous', english: 'The singer is famous.' },
    { wordId: 'beautiful', english: 'The flower is beautiful.' },
    { wordId: 'any', english: 'I do not have any questions.' },
    { wordId: 'few', english: 'I have a few books.' },

    // Level 7 · geography
    { wordId: 'country', english: 'This country is beautiful.' },
    { wordId: 'city', english: 'The city is busy.' },
    { wordId: 'town', english: 'This town is quiet.' },
    { wordId: 'village', english: 'The village is small.' },
    { wordId: 'island', english: 'We live on an island.' },
    { wordId: 'beach', english: 'We play on the beach.' },
    { wordId: 'forest', english: 'We walk in the forest.' },
    { wordId: 'field', english: 'The horse runs in the field.' },
    { wordId: 'lake', english: 'The lake is blue.' },
    { wordId: 'hill', english: 'We walk up the hill.' },

    // Level 7 · roads and travel
    { wordId: 'street', english: 'Our house is on this street.' },
    { wordId: 'road', english: 'The road is long.' },
    { wordId: 'corner', english: 'Turn at the corner.' },
    { wordId: 'traffic', english: 'The traffic is slow.' },
    { wordId: 'ticket', english: 'I have a train ticket.' },
    { wordId: 'seat', english: 'This seat is free.' },
    { wordId: 'trip', english: 'We have a fun trip.' },
    { wordId: 'travel', english: 'We travel by train.' },
    { wordId: 'way', english: 'This is the right way.' },
    { wordId: 'map', english: 'I look at the map.' },
    { wordId: 'life', english: 'Life is a gift.' },
    { wordId: 'health', english: 'Good food helps your health.' },
    { wordId: 'rest', english: 'I need a short rest.' },
    { wordId: 'job', english: 'My father has a job.' },
    { wordId: 'money', english: 'I save my money.' },
    { wordId: 'price', english: 'The price is high.' },
    { wordId: 'food', english: 'This food smells good.' },
    { wordId: 'clothes', english: 'My clothes are clean.' },
    { wordId: 'shoe', english: 'This shoe is new.' },
    { wordId: 'key', english: 'I have the key.' },

    // Level 7 · verbs
    { wordId: 'leave', english: 'I leave home at eight.' },
    { wordId: 'arrive', english: 'We arrive at the station.' },
    { wordId: 'reach', english: 'We reach the top.' },
    { wordId: 'pass', english: 'The bus will pass us.' },
    { wordId: 'cross', english: 'We cross the bridge.' },
    { wordId: 'enter', english: 'Please enter the room.' },
    { wordId: 'return', english: 'I return home at night.' },
    { wordId: 'follow', english: 'I follow my teacher.' },
    { wordId: 'send', english: 'I send a letter.' },
    { wordId: 'receive', english: 'I receive a gift.' },
    { wordId: 'buy', english: 'I buy a new book.' },
    { wordId: 'sell', english: 'They sell fresh fruit.' },
    { wordId: 'pay', english: 'I pay the price.' },
    { wordId: 'spend', english: 'I spend time with family.' },
    { wordId: 'save', english: 'I save my money.' },
    { wordId: 'borrow', english: 'I borrow a pencil.' },
    { wordId: 'lend', english: 'I lend my book.' },
    { wordId: 'own', english: 'I own a small bike.' },

    // Level 7 · adverbs and questions
    { wordId: 'soon', english: 'I will be home soon.' },
    { wordId: 'already', english: 'I have already eaten.' },
    { wordId: 'still', english: 'I am still learning.' },
    { wordId: 'yet', english: 'I have not finished yet.' },
    { wordId: 'ago', english: 'I saw him an hour ago.' },
    { wordId: 'then', english: 'We can play then.' },
    { wordId: 'outside', english: 'We play outside today.' },
    { wordId: 'inside', english: 'Come inside, please.' },
    { wordId: 'up', english: 'Look up at the sky.' },
    { wordId: 'down', english: 'Sit down on the chair.' },
    { wordId: 'back', english: 'Please come back soon.' },
    { wordId: 'when', english: 'I know when the bus comes.' },

    // Level 8 · learning and feelings
    { wordId: 'lesson', english: 'Our lesson starts now.' },
    { wordId: 'subject', english: 'Math is my favorite subject.' },
    { wordId: 'math', english: 'I study math at school.' },
    { wordId: 'science', english: 'We learn science at school.' },
    { wordId: 'history', english: 'I read about history.' },
    { wordId: 'music', english: 'I listen to music.' },
    { wordId: 'art', english: 'I like art.' },
    { wordId: 'sport', english: 'We play a sport.' },
    { wordId: 'language', english: 'English is a language.' },
    { wordId: 'feeling', english: 'I have a happy feeling.' },
    { wordId: 'heart', english: 'My heart beats fast.' },
    { wordId: 'mind', english: 'I keep this in mind.' },
    { wordId: 'dream', english: 'I have a big dream.' },
    { wordId: 'wish', english: 'I make a wish.' },
    { wordId: 'idea', english: 'That is a good idea.' },
    { wordId: 'plan', english: 'We have a plan.' },
    { wordId: 'problem', english: 'I can solve this problem.' },
    { wordId: 'reason', english: 'I know the reason.' },
    { wordId: 'thought', english: 'That thought is interesting.' },

    // Level 8 · events
    { wordId: 'party', english: 'We have a party today.' },
    { wordId: 'festival', english: 'We enjoy the spring festival.' },
    { wordId: 'birthday', english: 'Happy birthday, my friend.' },
    { wordId: 'Christmas', english: 'Christmas comes in winter.' },
    { wordId: 'vacation', english: 'We travel during vacation.' },
    { wordId: 'holiday', english: 'We rest on a holiday.' },
    { wordId: 'wedding', english: 'They have a beautiful wedding.' },
    { wordId: 'event', english: 'This event is special.' },

    // Level 8 · tools and media
    { wordId: 'camera', english: 'I use a camera.' },
    { wordId: 'computer', english: 'I use a computer at school.' },
    { wordId: 'TV', english: 'I watch TV at home.' },
    { wordId: 'radio', english: 'I listen to the radio.' },
    { wordId: 'newspaper', english: 'I read the newspaper.' },
    { wordId: 'magazine', english: 'I read a magazine.' },
    { wordId: 'letter', english: 'I write a letter.' },
    { wordId: 'card', english: 'I have a birthday card.' },
    { wordId: 'picture', english: 'I draw a picture.' },
    { wordId: 'photo', english: 'I take a photo.' },
    { wordId: 'game', english: 'We play a game.' },
    { wordId: 'movie', english: 'We watch a movie.' },
    { wordId: 'song', english: 'I sing a song.' },
    { wordId: 'story', english: 'I read a story.' },
    { wordId: 'news', english: 'I watch the news.' },
    { wordId: 'video', english: 'I watch a video.' },

    // Level 8 · verbs
    { wordId: 'remember', english: 'I remember your name.' },
    { wordId: 'forget', english: 'I never forget my key.' },
    { wordId: 'understand', english: 'I understand the question.' },
    { wordId: 'explain', english: 'I explain the answer.' },
    { wordId: 'believe', english: 'I believe my friend.' },
    { wordId: 'guess', english: 'I guess the answer.' },
    { wordId: 'wonder', english: 'I wonder about the world.' },
    { wordId: 'decide', english: 'We decide together.' },
    { wordId: 'choose', english: 'I choose a new book.' },
    { wordId: 'enjoy', english: 'I enjoy this game.' },
    { wordId: 'miss', english: 'I miss my family.' },
    { wordId: 'worry', english: 'I do not worry now.' },
    { wordId: 'surprise', english: 'You surprise me today.' },
    { wordId: 'please_lv8', english: 'Your words please my heart.' },
    { wordId: 'thank_lv8', english: 'I thank my teacher.' },
    { wordId: 'invite', english: 'I invite my friend.' },

    // Level 9 · verbs
    { wordId: 'change', english: 'I change my clothes.' },
    { wordId: 'break', english: 'Do not break the glass.' },
    { wordId: 'fix', english: 'I fix my bike.' },
    { wordId: 'cut', english: 'I cut the paper.' },
    { wordId: 'build', english: 'We build a new house.' },
    { wordId: 'create', english: 'I create a picture.' },
    { wordId: 'touch', english: 'Do not touch the fire.' },
    { wordId: 'hold', english: 'Hold my hand.' },
    { wordId: 'catch', english: 'I catch the ball.' },
    { wordId: 'throw', english: 'I throw the ball.' },
    { wordId: 'kick', english: 'I kick the ball.' },
    { wordId: 'hit', english: 'Do not hit the ball.' },
    { wordId: 'push', english: 'Push the door gently.' },
    { wordId: 'pull', english: 'Pull the box here.' },
    { wordId: 'drop', english: 'Do not drop the egg.' },
    { wordId: 'pick', english: 'I pick a flower.' },
    { wordId: 'smile', english: 'I smile at my friend.' },
    { wordId: 'cry', english: 'The baby can cry.' },
    { wordId: 'laugh', english: 'We laugh together.' },
    { wordId: 'shout', english: 'Please do not shout.' },
    { wordId: 'check', english: 'I check my answer.' },
    { wordId: 'practice', english: 'I practice every day.' },
    { wordId: 'prepare', english: 'I prepare my school bag.' },
    { wordId: 'hear', english: 'I hear a bird.' },
    { wordId: 'sound', english: 'I like this sound.' },

    // Level 9 · adjectives
    { wordId: 'kind', english: 'My teacher is kind.' },
    { wordId: 'gentle', english: 'The nurse is gentle.' },
    { wordId: 'brave', english: 'The brave girl can help.' },
    { wordId: 'honest', english: 'My friend is honest.' },
    { wordId: 'smart', english: 'The student is smart.' },
    { wordId: 'clever', english: 'The clever boy can solve it.' },
    { wordId: 'funny', english: 'The movie is funny.' },
    { wordId: 'serious', english: 'The teacher looks serious.' },
    { wordId: 'quiet', english: 'The library is quiet.' },
    { wordId: 'shy', english: 'The shy child says hello.' },
    { wordId: 'polite', english: 'The student is polite.' },
    { wordId: 'lazy', english: 'The cat is lazy.' },
    { wordId: 'busy', english: 'My mother is busy.' },
    { wordId: 'free', english: 'This seat is free.' },
    { wordId: 'ready', english: 'I am ready now.' },
    { wordId: 'safe', english: 'This place is safe.' },
    { wordId: 'dangerous', english: 'The fire is dangerous.' },
    { wordId: 'sick', english: 'The child is sick.' },
    { wordId: 'healthy', english: 'The food is healthy.' },
    { wordId: 'strong', english: 'The horse is strong.' },
    { wordId: 'weak', english: 'The small mouse is weak.' },
    { wordId: 'alive', english: 'The bird is alive.' },
    { wordId: 'dead', english: 'The flower is dead.' },

    // Level 9 · questions and adverbs
    { wordId: 'where', english: 'I know where she is.' },
    { wordId: 'why', english: 'I know why he left.' },
    { wordId: 'how', english: 'I know how to help.' },
    { wordId: 'which', english: 'I know which book you want.' },
    { wordId: 'whose', english: 'I know whose bag this is.' },
    { wordId: 'enough', english: 'I have enough time.' },
    { wordId: 'also', english: 'I also like music.' },
    { wordId: 'together', english: 'We learn together.' },
    { wordId: 'alone', english: 'I do not play alone.' },
    { wordId: 'well', english: 'I can read well.' },
    { wordId: 'hard_lv9', english: 'I work hard every day.' },
    { wordId: 'away', english: 'Please move away from the fire.' },

    // Level 10 · adjectives
    { wordId: 'pretty', english: 'The flower is pretty.' },
    { wordId: 'cute', english: 'The baby is cute.' },
    { wordId: 'handsome', english: 'The man is handsome.' },
    { wordId: 'ugly', english: 'The monster is ugly.' },
    { wordId: 'clean_lv10', english: 'My room is clean.' },
    { wordId: 'dirty', english: 'My shoes are dirty.' },
    { wordId: 'bright', english: 'The sun is bright.' },
    { wordId: 'dark', english: 'The night is dark.' },
    { wordId: 'loud', english: 'The music is loud.' },
    { wordId: 'popular', english: 'This game is popular.' },
    { wordId: 'special', english: 'Today is a special day.' },
    { wordId: 'wonderful', english: 'We had a wonderful day.' },
    { wordId: 'excellent', english: 'Your work is excellent.' },
    { wordId: 'perfect', english: 'This answer is perfect.' },
    { wordId: 'terrible', english: 'The weather is terrible.' },
    { wordId: 'strange', english: 'That sound is strange.' },
    { wordId: 'common', english: 'This is a common word.' },
    { wordId: 'useful', english: 'This map is useful.' },
    { wordId: 'lucky', english: 'I feel lucky today.' },
    { wordId: 'full', english: 'The box is full.' },
    { wordId: 'empty', english: 'The box is empty.' },
    { wordId: 'rich', english: 'The king is rich.' },
    { wordId: 'poor', english: 'The farmer is poor.' },
    { wordId: 'deep', english: 'The lake is deep.' },
    { wordId: 'thick', english: 'This book is thick.' },
    { wordId: 'thin', english: 'The paper is thin.' },
    { wordId: 'wide', english: 'The road is wide.' },
    { wordId: 'narrow', english: 'The street is narrow.' },
    { wordId: 'heavy', english: 'This bag is heavy.' },
    { wordId: 'light', english: 'This box is light.' },
    { wordId: 'early', english: 'I wake up early.' },
    { wordId: 'late', english: 'I am late today.' },
    { wordId: 'recent', english: 'I read a recent story.' },
    { wordId: 'next', english: 'The next lesson starts soon.' },
    { wordId: 'last', english: 'This is the last page.' },
    { wordId: 'own_lv10', english: 'This is my own room.' },
    { wordId: 'main', english: 'This is the main road.' },
    { wordId: 'real', english: 'This is a real story.' },
    { wordId: 'sure', english: 'I am sure now.' },

    // Level 10 · adverbs
    { wordId: 'again', english: 'Please try again.' },
    { wordId: 'once', english: 'I tried it once.' },
    { wordId: 'twice', english: 'I read it twice.' },
    { wordId: 'almost', english: 'I am almost ready.' },
    { wordId: 'nearly', english: 'It is nearly noon.' },
    { wordId: 'quite', english: 'This is quite easy.' },
    { wordId: 'rather', english: 'This book is rather thick.' },
    { wordId: 'especially', english: 'I like fruit, especially apples.' },
    { wordId: 'certainly', english: 'I can certainly help.' },
    { wordId: 'probably', english: 'It will probably rain.' },
    { wordId: 'maybe', english: 'Maybe we can play.' },
    { wordId: 'quickly', english: 'Run quickly to the bus.' },
    { wordId: 'slowly', english: 'Walk slowly, please.' },
    { wordId: 'carefully', english: 'I write carefully.' },
    { wordId: 'easily', english: 'I can easily read it.' },
    { wordId: 'suddenly', english: 'The wind suddenly changed.' },
    { wordId: 'quietly', english: 'Please close the door quietly.' },
    { wordId: 'loudly', english: 'The child laughed loudly.' },
    { wordId: 'daily', english: 'I practice English daily.' },
    { wordId: 'weekly', english: 'We meet weekly at school.' },
    { wordId: 'monthly', english: 'We have a monthly test.' },

    // Level 11 · society and environment
    { wordId: 'society', english: 'Society changes over time.' },
    { wordId: 'community', english: 'Our community is friendly.' },
    { wordId: 'government', english: 'The government makes laws.' },
    { wordId: 'law', english: 'We follow the law.' },
    { wordId: 'rule', english: 'This rule is important.' },
    { wordId: 'system', english: 'The system works well.' },
    { wordId: 'culture', english: 'I learn about culture.' },
    { wordId: 'tradition', english: 'This tradition is old.' },
    { wordId: 'environment', english: 'We care for the environment.' },
    { wordId: 'nature', english: 'I love nature.' },
    { wordId: 'world', english: 'The world is big.' },
    { wordId: 'space', english: 'Stars shine in space.' },
    { wordId: 'energy', english: 'The sun gives us energy.' },
    { wordId: 'power', english: 'This machine has power.' },
    { wordId: 'resource', english: 'Water is an important resource.' },

    // Level 11 · science and information
    { wordId: 'technology', english: 'Technology changes our lives.' },
    { wordId: 'research', english: 'The scientist does research.' },
    { wordId: 'experiment', english: 'We do an experiment.' },
    { wordId: 'discovery', english: 'This discovery is exciting.' },
    { wordId: 'invention', english: 'This invention is useful.' },
    { wordId: 'information', english: 'I need more information.' },
    { wordId: 'fact', english: 'This fact is true.' },
    { wordId: 'truth', english: 'I want to know the truth.' },
    { wordId: 'opinion', english: 'Everyone has an opinion.' },
    { wordId: 'example', english: 'This is an example.' },
    { wordId: 'result', english: 'The result is good.' },

    // Level 11 · activity and relationships
    { wordId: 'activity', english: 'This activity is fun.' },
    { wordId: 'experience', english: 'This is a new experience.' },
    { wordId: 'opportunity', english: 'This is a good opportunity.' },
    { wordId: 'challenge', english: 'I enjoy a new challenge.' },
    { wordId: 'success', english: 'Hard work brings success.' },
    { wordId: 'failure', english: 'Failure can teach us.' },
    { wordId: 'relationship', english: 'We have a good relationship.' },
    { wordId: 'communication', english: 'Good communication helps us.' },
    { wordId: 'conversation', english: 'We have a short conversation.' },
    { wordId: 'discussion', english: 'Our discussion starts now.' },
    { wordId: 'agreement', english: 'We reached an agreement.' },

    // Level 11 · adjectives and conjunctions
    { wordId: 'natural', english: 'This is a natural flower.' },
    { wordId: 'original', english: 'This is the original plan.' },
    { wordId: 'basic', english: 'I know the basic rules.' },
    { wordId: 'general', english: 'This is a general idea.' },
    { wordId: 'specific', english: 'Give one specific example.' },
    { wordId: 'available', english: 'The book is available here.' },
    { wordId: 'possible', english: 'It is possible to learn.' },
    { wordId: 'impossible', english: 'Nothing is impossible.' },
    { wordId: 'necessary', english: 'Rest is necessary today.' },
    { wordId: 'effective', english: 'This is an effective way.' },
    { wordId: 'and', english: 'I read and write.' },
    { wordId: 'but', english: 'I am tired, but I learn.' },
    { wordId: 'or', english: 'You can choose tea or juice.' },
    { wordId: 'so_lv11', english: 'I am tired, so I rest.' },
    { wordId: 'because', english: 'I rest because I am tired.' },
    { wordId: 'if', english: 'If it rains, I stay home.' },
    { wordId: 'though', english: 'Though it is hard, I try.' },
    { wordId: 'although', english: 'Although it rains, we still play.' },
    { wordId: 'before', english: 'Wash your hands before you eat.' },
    { wordId: 'after', english: 'We play after school.' },
    { wordId: 'while', english: 'While I read, my sister sleeps.' },
    { wordId: 'until', english: 'I wait until the bus comes.' },
    { wordId: 'since', english: 'I have lived here since Monday.' },

    // Level 12 · concepts
    { wordId: 'way_lv12', english: 'This is a good way.' },
    { wordId: 'method', english: 'This method is easy.' },
    { wordId: 'step', english: 'Take one step forward.' },
    { wordId: 'process', english: 'The process takes time.' },
    { wordId: 'progress', english: 'I can see progress.' },
    { wordId: 'effort', english: 'Your effort is important.' },
    { wordId: 'purpose', english: 'I know the purpose.' },
    { wordId: 'goal', english: 'I have a clear goal.' },
    { wordId: 'difference', english: 'I see the difference.' },
    { wordId: 'choice', english: 'This is my choice.' },

    // Level 12 · situations
    { wordId: 'situation', english: 'This situation is new.' },
    { wordId: 'condition', english: 'The plant is in good condition.' },
    { wordId: 'case', english: 'This is a special case.' },
    { wordId: 'scene', english: 'The scene is beautiful.' },
    { wordId: 'view', english: 'The view is beautiful.' },
    { wordId: 'point', english: 'I understand the point.' },
    { wordId: 'position', english: 'Change your position.' },
    { wordId: 'role', english: 'I know my role.' },
    { wordId: 'chance', english: 'I have a chance.' },
    { wordId: 'trouble', english: 'We can solve the trouble.' },

    // Level 12 · verbs
    { wordId: 'consider', english: 'I consider your idea.' },
    { wordId: 'realize', english: 'I realize the truth.' },
    { wordId: 'recognize', english: 'I recognize my friend.' },
    { wordId: 'notice', english: 'I notice the change.' },
    { wordId: 'imagine', english: 'I imagine a new world.' },
    { wordId: 'expect', english: 'I expect good news.' },
    { wordId: 'express', english: 'I express my feeling.' },
    { wordId: 'describe', english: 'I describe the picture.' },
    { wordId: 'introduce', english: 'I introduce my friend.' },
    { wordId: 'announce', english: 'They announce the result.' },
    { wordId: 'report', english: 'I report the problem.' },
    { wordId: 'suggest', english: 'I suggest a new plan.' },
    { wordId: 'mention', english: 'I mention the reason.' },
    { wordId: 'discuss', english: 'We discuss the problem.' },
    { wordId: 'act', english: 'We act in the play.' },
    { wordId: 'perform', english: 'They perform a song.' },
    { wordId: 'manage', english: 'I manage the work.' },
    { wordId: 'control', english: 'I control the machine.' },

    // Level 12 · feelings and judgments
    { wordId: 'excited', english: 'I am excited today.' },
    { wordId: 'interested', english: 'I am interested in art.' },
    { wordId: 'worried', english: 'I am worried about him.' },
    { wordId: 'disappointed', english: 'I am disappointed today.' },
    { wordId: 'satisfied', english: 'I am satisfied with lunch.' },
    { wordId: 'confused', english: 'I am confused by the question.' },
    { wordId: 'bored', english: 'I am bored at home.' },
    { wordId: 'surprised', english: 'I am surprised by the news.' },
    { wordId: 'correct', english: 'Your answer is correct.' },
    { wordId: 'proper', english: 'This is the proper way.' },
    { wordId: 'appropriate', english: 'This is an appropriate choice.' },
    { wordId: 'reasonable', english: 'That is a reasonable plan.' },
    { wordId: 'positive', english: 'I have a positive thought.' },
    { wordId: 'negative', english: 'This is a negative result.' },

    // Level 12 · connectors and other words
    { wordId: 'as', english: 'I work as a teacher.' },
    { wordId: 'than', english: 'This book is better than that.' },
    { wordId: 'either', english: 'You can choose either one.' },
    { wordId: 'both', english: 'Both children can play.' },
    { wordId: 'neither', english: 'Neither answer is correct.' },
    { wordId: 'even', english: 'Even the baby can smile.' },
    { wordId: 'of course', english: 'Of course, I can help.' },
    { wordId: 'for example', english: 'For example, an apple is red.' },
];

export const ENGLISH_EXAMPLE_SENTENCES: readonly EnglishExampleSentence[] = examples;

/**
 * Returns the fixed example for a vocabulary learning item.
 *
 * The lookup stays ID-based so saved problems keep the same behavior even if
 * the visible word is customized or legacy data is used.
 */
export function getEnglishExampleSentence(wordId: string): string | undefined {
    return ENGLISH_EXAMPLE_SENTENCES.find(sentence => sentence.wordId === wordId)?.english;
}
