export interface EnglishExampleSentence {
    wordId: string;
    english: string;
}

/**
 * Fixed starter examples for the vocabulary cards.
 *
 * This catalog is intentionally separate from the optional listening catalog:
 * a card can show a sentence without making that sentence eligible for the
 * listening offer or changing any learning progression.
 */
const examples: readonly EnglishExampleSentence[] = [
    // Level 1 · food
    { wordId: 'apple', english: 'This is an apple.' },
    { wordId: 'orange', english: 'This is an orange.' },
    { wordId: 'banana', english: 'This is a banana.' },
    { wordId: 'egg', english: 'This is an egg.' },
    { wordId: 'milk', english: 'I drink milk.' },
    { wordId: 'bread', english: 'I eat bread.' },
    { wordId: 'rice', english: 'I eat rice.' },
    { wordId: 'meat', english: 'I like meat.' },
    { wordId: 'water', english: 'I drink water.' },
    { wordId: 'juice', english: 'I drink juice.' },
    { wordId: 'cake', english: 'I like cake.' },
    { wordId: 'pizza', english: 'I like pizza.' },
    { wordId: 'candy', english: 'This candy is sweet.' },
    { wordId: 'vegetable', english: 'I eat a vegetable.' },
    { wordId: 'fruit', english: 'I like fruit.' },

    // Level 1 · animals
    { wordId: 'dog', english: 'This is a dog.' },
    { wordId: 'cat', english: 'Look at the cat.' },
    { wordId: 'bird', english: 'The bird can fly.' },
    { wordId: 'fish', english: 'The fish can swim.' },
    { wordId: 'rabbit', english: 'The rabbit is fast.' },
    { wordId: 'elephant', english: 'The elephant is big.' },
    { wordId: 'lion', english: 'The lion is strong.' },
    { wordId: 'tiger', english: 'The tiger can run.' },
    { wordId: 'monkey', english: 'The monkey can jump.' },
    { wordId: 'bear', english: 'The bear is big.' },
    { wordId: 'horse', english: 'The horse can run.' },
    { wordId: 'cow', english: 'The cow eats grass.' },
    { wordId: 'pig', english: 'The pig is pink.' },
    { wordId: 'mouse', english: 'The mouse is small.' },
    { wordId: 'sheep', english: 'The sheep has wool.' },

    // Level 1 · numbers
    { wordId: 'one', english: 'I have one apple.' },
    { wordId: 'two', english: 'I have two apples.' },
    { wordId: 'three', english: 'I have three apples.' },
    { wordId: 'four', english: 'I see four birds.' },
    { wordId: 'five', english: 'I see five stars.' },
    { wordId: 'six', english: 'I see six fish.' },
    { wordId: 'seven', english: 'I see seven flowers.' },
    { wordId: 'eight', english: 'I see eight balls.' },
    { wordId: 'nine', english: 'I see nine books.' },
    { wordId: 'ten', english: 'I can count to ten.' },
    { wordId: 'hundred', english: 'One hundred is a big number.' },
    { wordId: 'thousand', english: 'One thousand is a big number.' },

    // Level 1 · everyday words
    { wordId: 'yes', english: 'Yes, I can.' },
    { wordId: 'no', english: 'No, thank you.' },
    { wordId: 'hello', english: 'Hello, my friend.' },
    { wordId: 'goodbye', english: 'Goodbye, see you.' },
    { wordId: 'please', english: 'Please help me.' },
    { wordId: 'thank', english: 'Thank you very much.' },

    // Level 1 · adjectives
    { wordId: 'good', english: 'This apple is good.' },
    { wordId: 'bad', english: 'This candy is bad.' },
    { wordId: 'big', english: 'The elephant is big.' },
    { wordId: 'small', english: 'The mouse is small.' },
    { wordId: 'new', english: 'This is a new book.' },
    { wordId: 'old', english: 'This is an old tree.' },
    { wordId: 'hot', english: 'The soup is hot.' },
    { wordId: 'cold', english: 'The water is cold.' },
    { wordId: 'happy', english: 'I am happy today.' },
    { wordId: 'sad', english: 'The song is sad.' },

    // Level 1 · verbs
    { wordId: 'like', english: 'I like apples.' },
    { wordId: 'want', english: 'I want some juice.' },

    // Level 2 · body
    { wordId: 'head', english: 'This is my head.' },
    { wordId: 'face', english: 'Wash your face.' },
    { wordId: 'eye', english: 'I see with one eye.' },
    { wordId: 'ear', english: 'My ear can hear.' },
    { wordId: 'nose', english: 'Touch your nose.' },
    { wordId: 'mouth', english: 'Open your mouth.' },
    { wordId: 'hand', english: 'Hold my hand.' },
    { wordId: 'arm', english: 'Raise your arm.' },
    { wordId: 'leg', english: 'My leg is strong.' },
    { wordId: 'foot', english: 'My foot is small.' },
    { wordId: 'hair', english: 'Her hair is long.' },
    { wordId: 'finger', english: 'Point with one finger.' },
    { wordId: 'tooth', english: 'Brush one tooth.' },
    { wordId: 'neck', english: 'My neck is warm.' },
    { wordId: 'shoulder', english: 'Touch your shoulder.' },

    // Level 2 · family
    { wordId: 'father', english: 'My father is kind.' },
    { wordId: 'mother', english: 'My mother is kind.' },
    { wordId: 'brother', english: 'My brother can run.' },
    { wordId: 'sister', english: 'My sister can read.' },
    { wordId: 'family', english: 'I love my family.' },
    { wordId: 'baby', english: 'The baby is small.' },
    { wordId: 'parent', english: 'Ask your parent.' },
    { wordId: 'son', english: 'Their son can run.' },
    { wordId: 'daughter', english: 'Her daughter is happy.' },
    { wordId: 'grandfather', english: 'My grandfather tells stories.' },
    { wordId: 'grandmother', english: 'My grandmother is kind.' },

    // Level 2 · colors
    { wordId: 'red', english: 'The apple is red.' },
    { wordId: 'blue', english: 'The sky is blue.' },
    { wordId: 'green', english: 'The tree is green.' },
    { wordId: 'yellow', english: 'The flower is yellow.' },
    { wordId: 'white', english: 'The snow is white.' },
    { wordId: 'black', english: 'The cat is black.' },
    { wordId: 'pink', english: 'The pig is pink.' },
    { wordId: 'brown', english: 'The bear is brown.' },
    { wordId: 'purple', english: 'This flower is purple.' },
    { wordId: 'gray', english: 'The mouse is gray.' },
    { wordId: 'orange_lv2', english: 'The ball is orange.' },

    // Level 2 · people
    { wordId: 'boy', english: 'The boy can run.' },
    { wordId: 'girl', english: 'The girl can read.' },
    { wordId: 'man', english: 'The man is tall.' },
    { wordId: 'woman', english: 'The woman is kind.' },
    { wordId: 'child', english: 'The child can play.' },
    { wordId: 'friend', english: 'My friend is happy.' },
    { wordId: 'teacher', english: 'My teacher can help.' },
    { wordId: 'student', english: 'The student can read.' },

    // Level 2 · adjectives
    { wordId: 'long', english: 'The rope is long.' },
    { wordId: 'short', english: 'The pencil is short.' },
    { wordId: 'tall', english: 'The man is tall.' },
    { wordId: 'young', english: 'The child is young.' },
    { wordId: 'large', english: 'The elephant is large.' },
    { wordId: 'little', english: 'The baby is little.' },

    // Level 2 · verbs
    { wordId: 'eat', english: 'I eat an apple.' },
    { wordId: 'drink', english: 'I drink water.' },
    { wordId: 'have', english: 'I have a book.' },
    { wordId: 'see', english: 'I see a bird.' },
    { wordId: 'look', english: 'Look at the flower.' },
    { wordId: 'love', english: 'I love my family.' },
    { wordId: 'know', english: 'I know the answer.' },
    { wordId: 'think', english: 'I think of home.' },

    // Level 3 · places
    { wordId: 'house', english: 'This is my house.' },
    { wordId: 'home', english: 'I am at home.' },
    { wordId: 'room', english: 'This is my room.' },
    { wordId: 'school', english: 'I go to school.' },
    { wordId: 'park', english: 'We play in the park.' },
    { wordId: 'station', english: 'The train is at the station.' },
    { wordId: 'hospital', english: 'The doctor is at the hospital.' },
    { wordId: 'restaurant', english: 'We eat at the restaurant.' },
    { wordId: 'store', english: 'I go to the store.' },
    { wordId: 'library', english: 'I read at the library.' },

    // Level 3 · school
    { wordId: 'class', english: 'This is our class.' },
    { wordId: 'desk', english: 'My book is on the desk.' },
    { wordId: 'chair', english: 'Sit on the chair.' },
    { wordId: 'book', english: 'I read a book.' },
    { wordId: 'pen', english: 'I write with a pen.' },
    { wordId: 'pencil', english: 'I write with a pencil.' },
    { wordId: 'notebook', english: 'This is my notebook.' },
    { wordId: 'homework', english: 'I do my homework.' },
    { wordId: 'test', english: 'I take a test.' },
    { wordId: 'question', english: 'I have a question.' },

    // Level 3 · objects and transport
    { wordId: 'bag', english: 'My book is in the bag.' },
    { wordId: 'box', english: 'The ball is in the box.' },
    { wordId: 'door', english: 'Open the door, please.' },
    { wordId: 'window', english: 'Look out the window.' },
    { wordId: 'clock', english: 'The clock is on the wall.' },
    { wordId: 'phone', english: 'I use my phone.' },
    { wordId: 'car', english: 'I ride in a car.' },
    { wordId: 'bus', english: 'I ride the bus.' },
    { wordId: 'train', english: 'I see a train.' },
    { wordId: 'bike', english: 'I ride my bike.' },

    // Level 3 · verbs
    { wordId: 'go', english: 'I go to school.' },
    { wordId: 'come', english: 'Come to my home.' },
    { wordId: 'run', english: 'I can run fast.' },
    { wordId: 'walk', english: 'I walk to school.' },
    { wordId: 'stop', english: 'Please stop at the door.' },
    { wordId: 'sit', english: 'I sit on a chair.' },
    { wordId: 'stand', english: 'I stand by the door.' },
    { wordId: 'sleep', english: 'I sleep at home.' },
    { wordId: 'wake', english: 'I wake up early.' },
    { wordId: 'get', english: 'I get a new book.' },
    { wordId: 'put', english: 'Put the pen in the bag.' },
    { wordId: 'take', english: 'I take a bus.' },
    { wordId: 'give', english: 'I give my friend a book.' },
    { wordId: 'make', english: 'I make a paper plane.' },
    { wordId: 'do', english: 'I do my homework.' },
    { wordId: 'use', english: 'I use a pencil.' },
    { wordId: 'play', english: 'I play in the park.' },
    { wordId: 'work', english: 'I work at school.' },
    { wordId: 'study', english: 'I study at home.' },
    { wordId: 'read', english: 'I read a book.' },
    { wordId: 'write', english: 'I write in my notebook.' },
    { wordId: 'speak', english: 'I speak to my teacher.' },
    { wordId: 'say', english: 'I say hello.' },
    { wordId: 'tell', english: 'I tell my friend.' },
    { wordId: 'ask', english: 'I ask a question.' },
    { wordId: 'answer', english: 'I answer the question.' },
    { wordId: 'listen', english: 'I listen to my teacher.' },
    { wordId: 'watch', english: 'I watch the bird.' },
    { wordId: 'help', english: 'I help my family.' },
    { wordId: 'learn', english: 'I learn at school.' },

    // Level 4 · nature
    { wordId: 'sun', english: 'The sun is bright.' },
    { wordId: 'moon', english: 'The moon is bright.' },
    { wordId: 'star', english: 'I see a star.' },
    { wordId: 'sky', english: 'The sky is blue.' },
    { wordId: 'sea', english: 'The sea is wide.' },
    { wordId: 'mountain', english: 'The mountain is high.' },
    { wordId: 'river', english: 'The river is long.' },
    { wordId: 'tree', english: 'The tree is green.' },
    { wordId: 'flower', english: 'This flower is pretty.' },
    { wordId: 'rain', english: 'I like the rain.' },
    { wordId: 'snow', english: 'The snow is cold.' },
    { wordId: 'wind', english: 'The wind is strong.' },
    { wordId: 'cloud', english: 'A cloud is in the sky.' },
    { wordId: 'fire', english: 'The fire is hot.' },
    { wordId: 'earth', english: 'We live on Earth.' },

    // Level 4 · time
    { wordId: 'day', english: 'This is a sunny day.' },
    { wordId: 'night', english: 'The night is dark.' },
    { wordId: 'morning', english: 'Good morning, my friend.' },
    { wordId: 'afternoon', english: 'Good afternoon, teacher.' },
    { wordId: 'evening', english: 'Good evening, everyone.' },
    { wordId: 'week', english: 'This week is busy.' },
    { wordId: 'month', english: 'This month is long.' },
    { wordId: 'year', english: 'This year is new.' },
    { wordId: 'today', english: 'I am happy today.' },
    { wordId: 'tomorrow', english: 'We can play tomorrow.' },
    { wordId: 'yesterday', english: 'We played yesterday.' },
    { wordId: 'now', english: 'I am ready now.' },
    { wordId: 'time', english: 'I have time to play.' },
    { wordId: 'hour', english: 'One hour is enough.' },
    { wordId: 'minute', english: 'Wait one minute, please.' },

    // Level 4 · verbs
    { wordId: 'open', english: 'Open the window, please.' },
    { wordId: 'close', english: 'Close the door, please.' },
    { wordId: 'turn', english: 'Turn left at the corner.' },
    { wordId: 'move', english: 'Move the chair, please.' },
    { wordId: 'fly', english: 'Birds can fly high.' },
    { wordId: 'swim', english: 'Fish can swim well.' },
    { wordId: 'jump', english: 'I can jump high.' },
    { wordId: 'start', english: 'We start the game now.' },
    { wordId: 'begin', english: 'We begin our lesson.' },
    { wordId: 'finish', english: 'I finish my homework.' },
    { wordId: 'end', english: 'The game will end soon.' },
    { wordId: 'wait', english: 'Please wait for me.' },
    { wordId: 'call', english: 'I call my friend.' },
    { wordId: 'bring', english: 'Bring your book here.' },
    { wordId: 'keep', english: 'Keep your room clean.' },
    { wordId: 'find', english: 'I find my key.' },
    { wordId: 'lose', english: 'I never lose my bag.' },
    { wordId: 'win', english: 'We can win this game.' },
    { wordId: 'try', english: 'I try again.' },
    { wordId: 'feel', english: 'I feel happy today.' },
    { wordId: 'become', english: 'I want to become strong.' },
    { wordId: 'grow', english: 'Plants grow in the sun.' },
    { wordId: 'need', english: 'I need some water.' },
    { wordId: 'hope', english: 'I hope you are well.' },
    { wordId: 'sing', english: 'We sing a song.' },
    { wordId: 'dance', english: 'We dance at the party.' },
    { wordId: 'draw', english: 'I draw a picture.' },
    { wordId: 'show', english: 'Show me your picture.' },
    { wordId: 'meet', english: 'I meet my friend.' },
    { wordId: 'talk', english: 'We talk after class.' },

    // Level 5 · days and months
    { wordId: 'Sunday', english: 'We play on Sunday.' },
    { wordId: 'Monday', english: 'School starts on Monday.' },
    { wordId: 'Tuesday', english: 'I read on Tuesday.' },
    { wordId: 'Wednesday', english: 'We meet on Wednesday.' },
    { wordId: 'Thursday', english: 'I study on Thursday.' },
    { wordId: 'Friday', english: 'Friday is a school day.' },
    { wordId: 'Saturday', english: 'I rest on Saturday.' },
    { wordId: 'January', english: 'January is cold here.' },
    { wordId: 'February', english: 'February is a short month.' },
    { wordId: 'March', english: 'Flowers grow in March.' },
    { wordId: 'April', english: 'Rain falls in April.' },
    { wordId: 'May', english: 'May is warm here.' },
    { wordId: 'June', english: 'Summer starts in June.' },
    { wordId: 'July', english: 'July is hot here.' },
    { wordId: 'August', english: 'We travel in August.' },
    { wordId: 'September', english: 'School starts in September.' },
    { wordId: 'October', english: 'Leaves fall in October.' },
    { wordId: 'November', english: 'November comes after October.' },
    { wordId: 'December', english: 'Christmas comes in December.' },
    { wordId: 'spring', english: 'Flowers grow in spring.' },
    { wordId: 'summer', english: 'We swim in summer.' },
    { wordId: 'fall', english: 'Leaves change in fall.' },
    { wordId: 'winter', english: 'Snow falls in winter.' },

    // Level 5 · adjectives
    { wordId: 'nice', english: 'This is a nice day.' },
    { wordId: 'great', english: 'You did a great job.' },
    { wordId: 'fine', english: 'I feel fine today.' },
    { wordId: 'high', english: 'The mountain is high.' },
    { wordId: 'low', english: 'The chair is low.' },
    { wordId: 'warm', english: 'The soup is warm.' },
    { wordId: 'cool', english: 'The evening is cool.' },
    { wordId: 'fast', english: 'The horse is fast.' },
    { wordId: 'slow', english: 'The turtle is slow.' },
    { wordId: 'easy', english: 'This game is easy.' },
    { wordId: 'difficult', english: 'This question is difficult.' },
    { wordId: 'hard', english: 'This work is hard.' },
    { wordId: 'soft', english: 'The pillow is soft.' },
    { wordId: 'right', english: 'Your answer is right.' },
    { wordId: 'wrong', english: 'That answer is wrong.' },
    { wordId: 'same', english: 'We have the same book.' },
    { wordId: 'different', english: 'This book is different.' },
    { wordId: 'many', english: 'I see many stars.' },
    { wordId: 'much', english: 'I do not have much time.' },
    { wordId: 'some', english: 'I have some candy.' },
    { wordId: 'all', english: 'All the children can play.' },
    { wordId: 'every', english: 'I read every day.' },

    // Level 5 · adverbs and questions
    { wordId: 'very', english: 'This is very nice.' },
    { wordId: 'really', english: 'I really like this song.' },
    { wordId: 'so', english: 'I am so happy.' },
    { wordId: 'too', english: 'This bag is too heavy.' },
    { wordId: 'just', english: 'I just got home.' },
    { wordId: 'only', english: 'I have only one book.' },
    { wordId: 'always', english: 'I always help my family.' },
    { wordId: 'usually', english: 'I usually walk to school.' },
    { wordId: 'often', english: 'I often read at home.' },
    { wordId: 'sometimes', english: 'I sometimes play outside.' },
    { wordId: 'never', english: 'I never lose my key.' },
    { wordId: 'here', english: 'Come and sit here.' },
    { wordId: 'there', english: 'Put the book there.' },
    { wordId: 'what', english: 'I know what you mean.' },
    { wordId: 'who', english: 'I know who she is.' },

    // Level 6 · people and jobs
    { wordId: 'people', english: 'Many people live here.' },
    { wordId: 'person', english: 'That person is kind.' },
    { wordId: 'neighbor', english: 'My neighbor has a dog.' },
    { wordId: 'guest', english: 'Our guest is here.' },
    { wordId: 'king', english: 'The king lives in a castle.' },
    { wordId: 'queen', english: 'The queen wears a crown.' },
    { wordId: 'doctor', english: 'The doctor helps people.' },
    { wordId: 'nurse', english: 'The nurse is kind.' },
    { wordId: 'police', english: 'The police keep us safe.' },
    { wordId: 'driver', english: 'The driver has a car.' },
    { wordId: 'cook', english: 'The cook makes lunch.' },
    { wordId: 'farmer', english: 'The farmer grows food.' },
    { wordId: 'singer', english: 'The singer sings a song.' },
    { wordId: 'player', english: 'The player kicks the ball.' },
    { wordId: 'artist', english: 'The artist draws a picture.' },
    { wordId: 'writer', english: 'The writer writes a story.' },
    { wordId: 'pilot', english: 'The pilot flies a plane.' },
    { wordId: 'scientist', english: 'The scientist does research.' },

    // Level 6 · buildings
    { wordId: 'building', english: 'This building is tall.' },
    { wordId: 'office', english: 'My father works in an office.' },
    { wordId: 'hotel', english: 'We stay at the hotel.' },
    { wordId: 'temple', english: 'The temple is old.' },
    { wordId: 'shrine', english: 'We visit the shrine.' },
    { wordId: 'castle', english: 'The castle is big.' },
    { wordId: 'tower', english: 'The tower is high.' },
    { wordId: 'bridge', english: 'We walk across the bridge.' },
    { wordId: 'church', english: 'The church has a tall tower.' },
    { wordId: 'museum', english: 'We see art at the museum.' },
    { wordId: 'airport', english: 'The plane is at the airport.' },
    { wordId: 'factory', english: 'The factory makes cars.' },

    // Level 6 · meals
    { wordId: 'breakfast', english: 'I eat breakfast at home.' },
    { wordId: 'lunch', english: 'We have lunch at noon.' },
    { wordId: 'dinner', english: 'We eat dinner together.' },
    { wordId: 'meal', english: 'This meal is good.' },
    { wordId: 'dish', english: 'This dish smells nice.' },
    { wordId: 'menu', english: 'I read the menu.' },
    { wordId: 'taste', english: 'The soup has a good taste.' },
    { wordId: 'smell', english: 'I like the smell.' },

    // Level 6 · verbs
    { wordId: 'live', english: 'I live with my family.' },
    { wordId: 'stay', english: 'We stay at home.' },
    { wordId: 'visit', english: 'I visit my grandmother.' },
    { wordId: 'join', english: 'Come and join our game.' },
    { wordId: 'clean', english: 'I clean my room.' },
    { wordId: 'wash', english: 'I wash my hands.' },
    { wordId: 'wear', english: 'I wear a warm coat.' },
    { wordId: 'carry', english: 'I carry my school bag.' },
    { wordId: 'die', english: 'Plants die without water.' },
    { wordId: 'born', english: 'I was born in spring.' },

    // Level 6 · adjectives
    { wordId: 'hungry', english: 'I am hungry now.' },
    { wordId: 'thirsty', english: 'I am thirsty now.' },
    { wordId: 'tired', english: 'I feel tired today.' },
    { wordId: 'angry', english: 'The boy is angry.' },
    { wordId: 'glad', english: 'I am glad to see you.' },
    { wordId: 'sorry', english: 'I am sorry, my friend.' },
    { wordId: 'true', english: 'This story is true.' },
    { wordId: 'important', english: 'Family is important to me.' },
    { wordId: 'famous', english: 'The singer is famous.' },
    { wordId: 'beautiful', english: 'The flower is beautiful.' },
    { wordId: 'any', english: 'I do not have any questions.' },
    { wordId: 'few', english: 'I have a few books.' },

    // Level 7 · geography
    { wordId: 'country', english: 'This country is beautiful.' },
    { wordId: 'city', english: 'The city is busy.' },
    { wordId: 'town', english: 'This town is quiet.' },
    { wordId: 'village', english: 'The village is small.' },
    { wordId: 'island', english: 'We live on an island.' },
    { wordId: 'beach', english: 'We play on the beach.' },
    { wordId: 'forest', english: 'We walk in the forest.' },
    { wordId: 'field', english: 'The horse runs in the field.' },
    { wordId: 'lake', english: 'The lake is blue.' },
    { wordId: 'hill', english: 'We walk up the hill.' },

    // Level 7 · roads and travel
    { wordId: 'street', english: 'Our house is on this street.' },
    { wordId: 'road', english: 'The road is long.' },
    { wordId: 'corner', english: 'Turn at the corner.' },
    { wordId: 'traffic', english: 'The traffic is slow.' },
    { wordId: 'ticket', english: 'I have a train ticket.' },
    { wordId: 'seat', english: 'This seat is free.' },
    { wordId: 'trip', english: 'We have a fun trip.' },
    { wordId: 'travel', english: 'We travel by train.' },
    { wordId: 'way', english: 'This is the right way.' },
    { wordId: 'map', english: 'I look at the map.' },
    { wordId: 'life', english: 'Life is a gift.' },
    { wordId: 'health', english: 'Good food helps your health.' },
    { wordId: 'rest', english: 'I need a short rest.' },
    { wordId: 'job', english: 'My father has a job.' },
    { wordId: 'money', english: 'I save my money.' },
    { wordId: 'price', english: 'The price is high.' },
    { wordId: 'food', english: 'This food smells good.' },
    { wordId: 'clothes', english: 'My clothes are clean.' },
    { wordId: 'shoe', english: 'This shoe is new.' },
    { wordId: 'key', english: 'I have the key.' },

    // Level 7 · verbs
    { wordId: 'leave', english: 'I leave home at eight.' },
    { wordId: 'arrive', english: 'We arrive at the station.' },
    { wordId: 'reach', english: 'We reach the top.' },
    { wordId: 'pass', english: 'The bus will pass us.' },
    { wordId: 'cross', english: 'We cross the bridge.' },
    { wordId: 'enter', english: 'Please enter the room.' },
    { wordId: 'return', english: 'I return home at night.' },
    { wordId: 'follow', english: 'I follow my teacher.' },
    { wordId: 'send', english: 'I send a letter.' },
    { wordId: 'receive', english: 'I receive a gift.' },
    { wordId: 'buy', english: 'I buy a new book.' },
    { wordId: 'sell', english: 'They sell fresh fruit.' },
    { wordId: 'pay', english: 'I pay the price.' },
    { wordId: 'spend', english: 'I spend time with family.' },
    { wordId: 'save', english: 'I save my money.' },
    { wordId: 'borrow', english: 'I borrow a pencil.' },
    { wordId: 'lend', english: 'I lend my book.' },
    { wordId: 'own', english: 'I own a small bike.' },

    // Level 7 · adverbs and questions
    { wordId: 'soon', english: 'I will be home soon.' },
    { wordId: 'already', english: 'I have already eaten.' },
    { wordId: 'still', english: 'I am still learning.' },
    { wordId: 'yet', english: 'I have not finished yet.' },
    { wordId: 'ago', english: 'I saw him an hour ago.' },
    { wordId: 'then', english: 'We can play then.' },
    { wordId: 'outside', english: 'We play outside today.' },
    { wordId: 'inside', english: 'Come inside, please.' },
    { wordId: 'up', english: 'Look up at the sky.' },
    { wordId: 'down', english: 'Sit down on the chair.' },
    { wordId: 'back', english: 'Please come back soon.' },
    { wordId: 'when', english: 'I know when the bus comes.' },

    // Level 8 · learning and feelings
    { wordId: 'lesson', english: 'Our lesson starts now.' },
    { wordId: 'subject', english: 'Math is my favorite subject.' },
    { wordId: 'math', english: 'I study math at school.' },
    { wordId: 'science', english: 'We learn science at school.' },
    { wordId: 'history', english: 'I read about history.' },
    { wordId: 'music', english: 'I listen to music.' },
    { wordId: 'art', english: 'I like art.' },
    { wordId: 'sport', english: 'We play a sport.' },
    { wordId: 'language', english: 'English is a language.' },
    { wordId: 'feeling', english: 'I have a happy feeling.' },
    { wordId: 'heart', english: 'My heart beats fast.' },
    { wordId: 'mind', english: 'I keep this in mind.' },
    { wordId: 'dream', english: 'I have a big dream.' },
    { wordId: 'wish', english: 'I make a wish.' },
    { wordId: 'idea', english: 'That is a good idea.' },
    { wordId: 'plan', english: 'We have a plan.' },
    { wordId: 'problem', english: 'I can solve this problem.' },
    { wordId: 'reason', english: 'I know the reason.' },
    { wordId: 'thought', english: 'That thought is interesting.' },

    // Level 8 · events
    { wordId: 'party', english: 'We have a party today.' },
    { wordId: 'festival', english: 'We enjoy the spring festival.' },
    { wordId: 'birthday', english: 'Happy birthday, my friend.' },
    { wordId: 'Christmas', english: 'Christmas comes in winter.' },
    { wordId: 'vacation', english: 'We travel during vacation.' },
    { wordId: 'holiday', english: 'We rest on a holiday.' },
    { wordId: 'wedding', english: 'They have a beautiful wedding.' },
    { wordId: 'event', english: 'This event is special.' },

    // Level 8 · tools and media
    { wordId: 'camera', english: 'I use a camera.' },
    { wordId: 'computer', english: 'I use a computer at school.' },
    { wordId: 'TV', english: 'I watch TV at home.' },
    { wordId: 'radio', english: 'I listen to the radio.' },
    { wordId: 'newspaper', english: 'I read the newspaper.' },
    { wordId: 'magazine', english: 'I read a magazine.' },
    { wordId: 'letter', english: 'I write a letter.' },
    { wordId: 'card', english: 'I have a birthday card.' },
    { wordId: 'picture', english: 'I draw a picture.' },
    { wordId: 'photo', english: 'I take a photo.' },
    { wordId: 'game', english: 'We play a game.' },
    { wordId: 'movie', english: 'We watch a movie.' },
    { wordId: 'song', english: 'I sing a song.' },
    { wordId: 'story', english: 'I read a story.' },
    { wordId: 'news', english: 'I watch the news.' },
    { wordId: 'video', english: 'I watch a video.' },

    // Level 8 · verbs
    { wordId: 'remember', english: 'I remember your name.' },
    { wordId: 'forget', english: 'I never forget my key.' },
    { wordId: 'understand', english: 'I understand the question.' },
    { wordId: 'explain', english: 'I explain the answer.' },
    { wordId: 'believe', english: 'I believe my friend.' },
    { wordId: 'guess', english: 'I guess the answer.' },
    { wordId: 'wonder', english: 'I wonder about the world.' },
    { wordId: 'decide', english: 'We decide together.' },
    { wordId: 'choose', english: 'I choose a new book.' },
    { wordId: 'enjoy', english: 'I enjoy this game.' },
    { wordId: 'miss', english: 'I miss my family.' },
    { wordId: 'worry', english: 'I do not worry now.' },
    { wordId: 'surprise', english: 'You surprise me today.' },
    { wordId: 'please_lv8', english: 'Your words please my heart.' },
    { wordId: 'thank_lv8', english: 'I thank my teacher.' },
    { wordId: 'invite', english: 'I invite my friend.' },

    // Level 9 · verbs
    { wordId: 'change', english: 'I change my clothes.' },
    { wordId: 'break', english: 'Do not break the glass.' },
    { wordId: 'fix', english: 'I fix my bike.' },
    { wordId: 'cut', english: 'I cut the paper.' },
    { wordId: 'build', english: 'We build a new house.' },
    { wordId: 'create', english: 'I create a picture.' },
    { wordId: 'touch', english: 'Do not touch the fire.' },
    { wordId: 'hold', english: 'Hold my hand.' },
    { wordId: 'catch', english: 'I catch the ball.' },
    { wordId: 'throw', english: 'I throw the ball.' },
    { wordId: 'kick', english: 'I kick the ball.' },
    { wordId: 'hit', english: 'Do not hit the ball.' },
    { wordId: 'push', english: 'Push the door gently.' },
    { wordId: 'pull', english: 'Pull the box here.' },
    { wordId: 'drop', english: 'Do not drop the egg.' },
    { wordId: 'pick', english: 'I pick a flower.' },
    { wordId: 'smile', english: 'I smile at my friend.' },
    { wordId: 'cry', english: 'The baby can cry.' },
    { wordId: 'laugh', english: 'We laugh together.' },
    { wordId: 'shout', english: 'Please do not shout.' },
    { wordId: 'check', english: 'I check my answer.' },
    { wordId: 'practice', english: 'I practice every day.' },
    { wordId: 'prepare', english: 'I prepare my school bag.' },
    { wordId: 'hear', english: 'I hear a bird.' },
    { wordId: 'sound', english: 'I like this sound.' },

    // Level 9 · adjectives
    { wordId: 'kind', english: 'My teacher is kind.' },
    { wordId: 'gentle', english: 'The nurse is gentle.' },
    { wordId: 'brave', english: 'The brave girl can help.' },
    { wordId: 'honest', english: 'My friend is honest.' },
    { wordId: 'smart', english: 'The student is smart.' },
    { wordId: 'clever', english: 'The clever boy can solve it.' },
    { wordId: 'funny', english: 'The movie is funny.' },
    { wordId: 'serious', english: 'The teacher looks serious.' },
    { wordId: 'quiet', english: 'The library is quiet.' },
    { wordId: 'shy', english: 'The shy child says hello.' },
    { wordId: 'polite', english: 'The student is polite.' },
    { wordId: 'lazy', english: 'The cat is lazy.' },
    { wordId: 'busy', english: 'My mother is busy.' },
    { wordId: 'free', english: 'This seat is free.' },
    { wordId: 'ready', english: 'I am ready now.' },
    { wordId: 'safe', english: 'This place is safe.' },
    { wordId: 'dangerous', english: 'The fire is dangerous.' },
    { wordId: 'sick', english: 'The child is sick.' },
    { wordId: 'healthy', english: 'The food is healthy.' },
    { wordId: 'strong', english: 'The horse is strong.' },
    { wordId: 'weak', english: 'The small mouse is weak.' },
    { wordId: 'alive', english: 'The bird is alive.' },
    { wordId: 'dead', english: 'The flower is dead.' },

    // Level 9 · questions and adverbs
    { wordId: 'where', english: 'I know where she is.' },
    { wordId: 'why', english: 'I know why he left.' },
    { wordId: 'how', english: 'I know how to help.' },
    { wordId: 'which', english: 'I know which book you want.' },
    { wordId: 'whose', english: 'I know whose bag this is.' },
    { wordId: 'enough', english: 'I have enough time.' },
    { wordId: 'also', english: 'I also like music.' },
    { wordId: 'together', english: 'We learn together.' },
    { wordId: 'alone', english: 'I do not play alone.' },
    { wordId: 'well', english: 'I can read well.' },
    { wordId: 'hard_lv9', english: 'I work hard every day.' },
    { wordId: 'away', english: 'Please move away from the fire.' },

    // Level 10 · adjectives
    { wordId: 'pretty', english: 'The flower is pretty.' },
    { wordId: 'cute', english: 'The baby is cute.' },
    { wordId: 'handsome', english: 'The man is handsome.' },
    { wordId: 'ugly', english: 'The monster is ugly.' },
    { wordId: 'clean_lv10', english: 'My room is clean.' },
    { wordId: 'dirty', english: 'My shoes are dirty.' },
    { wordId: 'bright', english: 'The sun is bright.' },
    { wordId: 'dark', english: 'The night is dark.' },
    { wordId: 'loud', english: 'The music is loud.' },
    { wordId: 'popular', english: 'This game is popular.' },
    { wordId: 'special', english: 'Today is a special day.' },
    { wordId: 'wonderful', english: 'We had a wonderful day.' },
    { wordId: 'excellent', english: 'Your work is excellent.' },
    { wordId: 'perfect', english: 'This answer is perfect.' },
    { wordId: 'terrible', english: 'The weather is terrible.' },
    { wordId: 'strange', english: 'That sound is strange.' },
    { wordId: 'common', english: 'This is a common word.' },
    { wordId: 'useful', english: 'This map is useful.' },
    { wordId: 'lucky', english: 'I feel lucky today.' },
    { wordId: 'full', english: 'The box is full.' },
    { wordId: 'empty', english: 'The box is empty.' },
    { wordId: 'rich', english: 'The king is rich.' },
    { wordId: 'poor', english: 'The farmer is poor.' },
    { wordId: 'deep', english: 'The lake is deep.' },
    { wordId: 'thick', english: 'This book is thick.' },
    { wordId: 'thin', english: 'The paper is thin.' },
    { wordId: 'wide', english: 'The road is wide.' },
    { wordId: 'narrow', english: 'The street is narrow.' },
    { wordId: 'heavy', english: 'This bag is heavy.' },
    { wordId: 'light', english: 'This box is light.' },
    { wordId: 'early', english: 'I wake up early.' },
    { wordId: 'late', english: 'I am late today.' },
    { wordId: 'recent', english: 'I read a recent story.' },
    { wordId: 'next', english: 'The next lesson starts soon.' },
    { wordId: 'last', english: 'This is the last page.' },
    { wordId: 'own_lv10', english: 'This is my own room.' },
    { wordId: 'main', english: 'This is the main road.' },
    { wordId: 'real', english: 'This is a real story.' },
    { wordId: 'sure', english: 'I am sure now.' },

    // Level 10 · adverbs
    { wordId: 'again', english: 'Please try again.' },
    { wordId: 'once', english: 'I tried it once.' },
    { wordId: 'twice', english: 'I read it twice.' },
    { wordId: 'almost', english: 'I am almost ready.' },
    { wordId: 'nearly', english: 'It is nearly noon.' },
    { wordId: 'quite', english: 'This is quite easy.' },
    { wordId: 'rather', english: 'This book is rather thick.' },
    { wordId: 'especially', english: 'I like fruit, especially apples.' },
    { wordId: 'certainly', english: 'I can certainly help.' },
    { wordId: 'probably', english: 'It will probably rain.' },
    { wordId: 'maybe', english: 'Maybe we can play.' },
    { wordId: 'quickly', english: 'Run quickly to the bus.' },
    { wordId: 'slowly', english: 'Walk slowly, please.' },
    { wordId: 'carefully', english: 'I write carefully.' },
    { wordId: 'easily', english: 'I can easily read it.' },
    { wordId: 'suddenly', english: 'The wind suddenly changed.' },
    { wordId: 'quietly', english: 'Please close the door quietly.' },
    { wordId: 'loudly', english: 'The child laughed loudly.' },
    { wordId: 'daily', english: 'I practice English daily.' },
    { wordId: 'weekly', english: 'We meet weekly at school.' },
    { wordId: 'monthly', english: 'We have a monthly test.' },

    // Level 11 · society and environment
    { wordId: 'society', english: 'Society changes over time.' },
    { wordId: 'community', english: 'Our community is friendly.' },
    { wordId: 'government', english: 'The government makes laws.' },
    { wordId: 'law', english: 'We follow the law.' },
    { wordId: 'rule', english: 'This rule is important.' },
    { wordId: 'system', english: 'The system works well.' },
    { wordId: 'culture', english: 'I learn about culture.' },
    { wordId: 'tradition', english: 'This tradition is old.' },
    { wordId: 'environment', english: 'We care for the environment.' },
    { wordId: 'nature', english: 'I love nature.' },
    { wordId: 'world', english: 'The world is big.' },
    { wordId: 'space', english: 'Stars shine in space.' },
    { wordId: 'energy', english: 'The sun gives us energy.' },
    { wordId: 'power', english: 'This machine has power.' },
    { wordId: 'resource', english: 'Water is an important resource.' },

    // Level 11 · science and information
    { wordId: 'technology', english: 'Technology changes our lives.' },
    { wordId: 'research', english: 'The scientist does research.' },
    { wordId: 'experiment', english: 'We do an experiment.' },
    { wordId: 'discovery', english: 'This discovery is exciting.' },
    { wordId: 'invention', english: 'This invention is useful.' },
    { wordId: 'information', english: 'I need more information.' },
    { wordId: 'fact', english: 'This fact is true.' },
    { wordId: 'truth', english: 'I want to know the truth.' },
    { wordId: 'opinion', english: 'Everyone has an opinion.' },
    { wordId: 'example', english: 'This is an example.' },
    { wordId: 'result', english: 'The result is good.' },

    // Level 11 · activity and relationships
    { wordId: 'activity', english: 'This activity is fun.' },
    { wordId: 'experience', english: 'This is a new experience.' },
    { wordId: 'opportunity', english: 'This is a good opportunity.' },
    { wordId: 'challenge', english: 'I enjoy a new challenge.' },
    { wordId: 'success', english: 'Hard work brings success.' },
    { wordId: 'failure', english: 'Failure can teach us.' },
    { wordId: 'relationship', english: 'We have a good relationship.' },
    { wordId: 'communication', english: 'Good communication helps us.' },
    { wordId: 'conversation', english: 'We have a short conversation.' },
    { wordId: 'discussion', english: 'Our discussion starts now.' },
    { wordId: 'agreement', english: 'We reached an agreement.' },

    // Level 11 · adjectives and conjunctions
    { wordId: 'natural', english: 'This is a natural flower.' },
    { wordId: 'original', english: 'This is the original plan.' },
    { wordId: 'basic', english: 'I know the basic rules.' },
    { wordId: 'general', english: 'This is a general idea.' },
    { wordId: 'specific', english: 'Give one specific example.' },
    { wordId: 'available', english: 'The book is available here.' },
    { wordId: 'possible', english: 'It is possible to learn.' },
    { wordId: 'impossible', english: 'Nothing is impossible.' },
    { wordId: 'necessary', english: 'Rest is necessary today.' },
    { wordId: 'effective', english: 'This is an effective way.' },
    { wordId: 'and', english: 'I read and write.' },
    { wordId: 'but', english: 'I am tired, but I learn.' },
    { wordId: 'or', english: 'You can choose tea or juice.' },
    { wordId: 'so_lv11', english: 'I am tired, so I rest.' },
    { wordId: 'because', english: 'I rest because I am tired.' },
    { wordId: 'if', english: 'If it rains, I stay home.' },
    { wordId: 'though', english: 'Though it is hard, I try.' },
    { wordId: 'although', english: 'Although it rains, we still play.' },
    { wordId: 'before', english: 'Wash your hands before you eat.' },
    { wordId: 'after', english: 'We play after school.' },
    { wordId: 'while', english: 'While I read, my sister sleeps.' },
    { wordId: 'until', english: 'I wait until the bus comes.' },
    { wordId: 'since', english: 'I have lived here since Monday.' },

    // Level 12 · concepts
    { wordId: 'way_lv12', english: 'This is a good way.' },
    { wordId: 'method', english: 'This method is easy.' },
    { wordId: 'step', english: 'Take one step forward.' },
    { wordId: 'process', english: 'The process takes time.' },
    { wordId: 'progress', english: 'I can see progress.' },
    { wordId: 'effort', english: 'Your effort is important.' },
    { wordId: 'purpose', english: 'I know the purpose.' },
    { wordId: 'goal', english: 'I have a clear goal.' },
    { wordId: 'difference', english: 'I see the difference.' },
    { wordId: 'choice', english: 'This is my choice.' },

    // Level 12 · situations
    { wordId: 'situation', english: 'This situation is new.' },
    { wordId: 'condition', english: 'The plant is in good condition.' },
    { wordId: 'case', english: 'This is a special case.' },
    { wordId: 'scene', english: 'The scene is beautiful.' },
    { wordId: 'view', english: 'The view is beautiful.' },
    { wordId: 'point', english: 'I understand the point.' },
    { wordId: 'position', english: 'Change your position.' },
    { wordId: 'role', english: 'I know my role.' },
    { wordId: 'chance', english: 'I have a chance.' },
    { wordId: 'trouble', english: 'We can solve the trouble.' },

    // Level 12 · verbs
    { wordId: 'consider', english: 'I consider your idea.' },
    { wordId: 'realize', english: 'I realize the truth.' },
    { wordId: 'recognize', english: 'I recognize my friend.' },
    { wordId: 'notice', english: 'I notice the change.' },
    { wordId: 'imagine', english: 'I imagine a new world.' },
    { wordId: 'expect', english: 'I expect good news.' },
    { wordId: 'express', english: 'I express my feeling.' },
    { wordId: 'describe', english: 'I describe the picture.' },
    { wordId: 'introduce', english: 'I introduce my friend.' },
    { wordId: 'announce', english: 'They announce the result.' },
    { wordId: 'report', english: 'I report the problem.' },
    { wordId: 'suggest', english: 'I suggest a new plan.' },
    { wordId: 'mention', english: 'I mention the reason.' },
    { wordId: 'discuss', english: 'We discuss the problem.' },
    { wordId: 'act', english: 'We act in the play.' },
    { wordId: 'perform', english: 'They perform a song.' },
    { wordId: 'manage', english: 'I manage the work.' },
    { wordId: 'control', english: 'I control the machine.' },

    // Level 12 · feelings and judgments
    { wordId: 'excited', english: 'I am excited today.' },
    { wordId: 'interested', english: 'I am interested in art.' },
    { wordId: 'worried', english: 'I am worried about him.' },
    { wordId: 'disappointed', english: 'I am disappointed today.' },
    { wordId: 'satisfied', english: 'I am satisfied with lunch.' },
    { wordId: 'confused', english: 'I am confused by the question.' },
    { wordId: 'bored', english: 'I am bored at home.' },
    { wordId: 'surprised', english: 'I am surprised by the news.' },
    { wordId: 'correct', english: 'Your answer is correct.' },
    { wordId: 'proper', english: 'This is the proper way.' },
    { wordId: 'appropriate', english: 'This is an appropriate choice.' },
    { wordId: 'reasonable', english: 'That is a reasonable plan.' },
    { wordId: 'positive', english: 'I have a positive thought.' },
    { wordId: 'negative', english: 'This is a negative result.' },

    // Level 12 · connectors and other words
    { wordId: 'as', english: 'I work as a teacher.' },
    { wordId: 'than', english: 'This book is better than that.' },
    { wordId: 'either', english: 'You can choose either one.' },
    { wordId: 'both', english: 'Both children can play.' },
    { wordId: 'neither', english: 'Neither answer is correct.' },
    { wordId: 'even', english: 'Even the baby can smile.' },
    { wordId: 'of course', english: 'Of course, I can help.' },
    { wordId: 'for example', english: 'For example, an apple is red.' },

    // Level 13 · feelings, time, amounts, and degree
    { wordId: 'joy', english: 'Joy fills my heart.' },
    { wordId: 'fear', english: 'I face my fear.' },
    { wordId: 'anger', english: 'I calm my anger.' },
    { wordId: 'pain', english: 'The pain is gone.' },
    { wordId: 'stress', english: 'Rest helps my stress.' },
    { wordId: 'pressure', english: 'The pressure is high.' },
    { wordId: 'confidence', english: 'Practice builds confidence.' },
    { wordId: 'pride', english: 'I feel pride today.' },
    { wordId: 'interest', english: 'I have interest in art.' },
    { wordId: 'attention', english: 'Please pay attention.' },
    { wordId: 'moment', english: 'Wait a moment, please.' },
    { wordId: 'period', english: 'This period is important.' },
    { wordId: 'century', english: 'A century is long.' },
    { wordId: 'age', english: 'Your age is a number.' },
    { wordId: 'generation', english: 'Each generation learns new things.' },
    { wordId: 'future', english: 'The future is bright.' },
    { wordId: 'past', english: 'I learn from the past.' },
    { wordId: 'present', english: 'This present is for you.' },
    { wordId: 'type', english: 'This type is common.' },
    { wordId: 'form', english: 'Please fill out this form.' },
    { wordId: 'state', english: 'The state of water changes.' },
    { wordId: 'level', english: 'This level is difficult.' },
    { wordId: 'rate', english: 'The rate is very low.' },
    { wordId: 'amount', english: 'I need a small amount.' },
    { wordId: 'number', english: 'This number is large.' },
    { wordId: 'part', english: 'This is one part.' },
    { wordId: 'member', english: 'I am a team member.' },
    { wordId: 'group', english: 'We work in a group.' },
    { wordId: 'team', english: 'Our team can win.' },
    { wordId: 'leader', english: 'The leader helps the team.' },
    { wordId: 'huge', english: 'The elephant is huge.' },
    { wordId: 'tiny', english: 'The mouse is tiny.' },
    { wordId: 'enormous', english: 'The mountain is enormous.' },
    { wordId: 'total', english: 'The total is ten.' },
    { wordId: 'entire', english: 'I read the entire book.' },
    { wordId: 'various', english: 'We saw various flowers.' },
    { wordId: 'several', english: 'I have several books.' },
    { wordId: 'whole', english: 'I ate the whole cake.' },
    { wordId: 'single', english: 'I need a single ticket.' },
    { wordId: 'current', english: 'The current plan is good.' },
    { wordId: 'previous', english: 'I remember the previous lesson.' },
    { wordId: 'final', english: 'This is the final answer.' },
    { wordId: 'following', english: 'Read the following sentence.' },
    { wordId: 'major', english: 'This is a major change.' },
    { wordId: 'minor', english: 'This is a minor problem.' },
    { wordId: 'extremely', english: 'The mountain is extremely high.' },
    { wordId: 'completely', english: 'The box is completely empty.' },
    { wordId: 'totally', english: 'I totally agree with you.' },
    { wordId: 'absolutely', english: 'You are absolutely right.' },
    { wordId: 'hardly', english: 'I can hardly hear you.' },
    { wordId: 'barely', english: 'I can barely see it.' },
    { wordId: 'eventually', english: 'We will eventually succeed.' },
    { wordId: 'finally', english: 'I finally finished my work.' },
    { wordId: 'immediately', english: 'Please come immediately.' },
    { wordId: 'recently', english: 'I recently read this book.' },
    { wordId: 'currently', english: 'I am currently busy.' },
    { wordId: 'nowadays', english: 'Nowadays, people use phones.' },
    { wordId: 'originally', english: 'This was originally a school.' },
    { wordId: 'definitely', english: 'I will definitely help.' },
    { wordId: 'obviously', english: 'The answer is obviously right.' },

    // Level 14 · actions, relationships, and connectors
    { wordId: 'achieve', english: 'I can achieve my goal.' },
    { wordId: 'succeed', english: 'We can succeed together.' },
    { wordId: 'fail', english: 'I try again when I fail.' },
    { wordId: 'complete', english: 'I complete my homework.' },
    { wordId: 'accomplish', english: 'I accomplish a hard task.' },
    { wordId: 'overcome', english: 'We can overcome this problem.' },
    { wordId: 'connect', english: 'I connect the two boxes.' },
    { wordId: 'relate', english: 'I relate this story to home.' },
    { wordId: 'compare', english: 'We compare the two answers.' },
    { wordId: 'match', english: 'These colors match well.' },
    { wordId: 'combine', english: 'We combine red and blue.' },
    { wordId: 'separate', english: 'Please separate the two groups.' },
    { wordId: 'share', english: 'I share my book.' },
    { wordId: 'include', english: 'Please include a map.' },
    { wordId: 'affect', english: 'Rain can affect our trip.' },
    { wordId: 'influence', english: 'Friends influence our choices.' },
    { wordId: 'cause', english: 'Too much rain can cause trouble.' },
    { wordId: 'prevent', english: 'Warm clothes prevent the cold.' },
    { wordId: 'protect', english: 'We protect the environment.' },
    { wordId: 'support', english: 'My friends support me.' },
    { wordId: 'encourage', english: 'Teachers encourage students.' },
    { wordId: 'depend', english: 'Plants depend on water.' },
    { wordId: 'improve', english: 'Practice can improve skills.' },
    { wordId: 'increase', english: 'We increase the number.' },
    { wordId: 'decrease', english: 'The price can decrease.' },
    { wordId: 'reduce', english: 'We reduce food waste.' },
    { wordId: 'spread', english: 'The news can spread quickly.' },
    { wordId: 'extend', english: 'We extend the bridge.' },
    { wordId: 'expand', english: 'The city will expand.' },
    { wordId: 'agree', english: 'I agree with you.' },
    { wordId: 'disagree', english: 'We can disagree kindly.' },
    { wordId: 'accept', english: 'I accept your answer.' },
    { wordId: 'refuse', english: 'I refuse the offer.' },
    { wordId: 'allow', english: 'Rules allow us to play.' },
    { wordId: 'permit', english: 'This ticket permits entry.' },
    { wordId: 'require', english: 'This task requires time.' },
    { wordId: 'demand', english: 'They demand a fair price.' },
    { wordId: 'offer', english: 'I offer my help.' },
    { wordId: 'provide', english: 'We provide clean water.' },
    { wordId: 'supply', english: 'The river supplies water.' },
    { wordId: 'social', english: 'This is a social event.' },
    { wordId: 'public', english: 'The park is public.' },
    { wordId: 'private', english: 'This is my private room.' },
    { wordId: 'official', english: 'This is the official plan.' },
    { wordId: 'professional', english: 'The artist is professional.' },
    { wordId: 'personal', english: 'This is my personal choice.' },
    { wordId: 'local', english: 'We buy local food.' },
    { wordId: 'global', english: 'This is a global problem.' },
    { wordId: 'familiar', english: 'This place feels familiar.' },
    { wordId: 'similar', english: 'These two pictures are similar.' },
    { wordId: 'equal', english: 'The two parts are equal.' },
    { wordId: 'opposite', english: 'The two answers are opposite.' },
    { wordId: 'however', english: 'It is hard; however, I try.' },
    { wordId: 'therefore', english: 'I am tired; therefore, I rest.' },
    { wordId: 'moreover', english: 'It is cold; moreover, it is windy.' },
    { wordId: 'furthermore', english: 'The plan is safe; furthermore, it helps.' },
    { wordId: 'otherwise', english: 'Hurry, otherwise we will be late.' },
    { wordId: 'instead', english: 'I chose tea instead.' },
    { wordId: 'besides', english: 'Besides, I have a plan.' },
    { wordId: 'thus', english: 'It was late; thus, we went home.' },

    // Level 15 · abstract actions, qualities, and phrases
    { wordId: 'represent', english: 'This picture represents our family.' },
    { wordId: 'reflect', english: 'The lake reflects the sky.' },
    { wordId: 'contain', english: 'This box contains a gift.' },
    { wordId: 'involve', english: 'This game involves teamwork.' },
    { wordId: 'exist', english: 'Dragons do not exist.' },
    { wordId: 'appear', english: 'Stars appear at night.' },
    { wordId: 'disappear', english: 'Clouds disappear in wind.' },
    { wordId: 'remain', english: 'Please remain in your seat.' },
    { wordId: 'continue', english: 'Please continue your work.' },
    { wordId: 'maintain', english: 'We maintain a clean room.' },
    { wordId: 'apply', english: 'I apply the new rule.' },
    { wordId: 'solve', english: 'We solve the problem.' },
    { wordId: 'prove', english: 'I can prove my answer.' },
    { wordId: 'determine', english: 'We determine the right path.' },
    { wordId: 'predict', english: 'I predict rain tomorrow.' },
    { wordId: 'assume', english: 'Do not assume the answer.' },
    { wordId: 'handle', english: 'I can handle this task.' },
    { wordId: 'operate', english: 'This machine can operate safely.' },
    { wordId: 'produce', english: 'Plants produce fresh food.' },
    { wordId: 'develop', english: 'Children develop new skills.' },
    { wordId: 'action', english: 'Every action has a result.' },
    { wordId: 'effect', english: 'The rain has an effect.' },
    { wordId: 'cause_lv15', english: 'The cause is not clear.' },
    { wordId: 'sense', english: 'I sense a change.' },
    { wordId: 'meaning', english: 'I know the meaning.' },
    { wordId: 'value', english: 'This book has value.' },
    { wordId: 'service', english: 'The hotel offers good service.' },
    { wordId: 'project', english: 'We finish the project.' },
    { wordId: 'program', english: 'This program is useful.' },
    { wordId: 'matter', english: 'This matter is important.' },
    { wordId: 'active', english: 'The child is active.' },
    { wordId: 'successful', english: 'The project is successful.' },
    { wordId: 'physical', english: 'We need physical exercise.' },
    { wordId: 'mental', english: 'Rest supports mental health.' },
    { wordId: 'certain', english: 'I am certain now.' },
    { wordId: 'worth', english: 'This book is worth reading.' },
    { wordId: 'responsible', english: 'We are responsible for our choices.' },
    { wordId: 'further', english: 'We need further information.' },
    { wordId: 'former', english: 'My former teacher is kind.' },
    { wordId: 'fair', english: 'This is a fair rule.' },
    { wordId: 'simply', english: 'I simply need more time.' },
    { wordId: 'directly', english: 'Please speak directly to me.' },
    { wordId: 'generally', english: 'People generally like music.' },
    { wordId: 'normally', english: 'I normally walk to school.' },
    { wordId: 'properly', english: 'Please use the tool properly.' },
    { wordId: 'exactly', english: 'That is exactly right.' },
    { wordId: 'particularly', english: 'I particularly like this song.' },
    { wordId: 'specifically', english: 'Please answer specifically.' },
    { wordId: 'relatively', english: 'This task is relatively easy.' },
    { wordId: 'apparently', english: 'Apparently, the bus is late.' },
    { wordId: 'actually', english: 'I actually know the answer.' },
    { wordId: 'fortunately', english: 'Fortunately, we are safe.' },
    { wordId: 'unfortunately', english: 'Unfortunately, the shop is closed.' },
    { wordId: 'clearly', english: 'The answer is clearly right.' },
    { wordId: 'according to', english: 'According to the map, go left.' },
    { wordId: 'in addition', english: 'In addition, bring your book.' },
    { wordId: 'in fact', english: 'In fact, I know the answer.' },
    { wordId: 'at least', english: 'At least, we tried our best.' },
    { wordId: 'in general', english: 'In general, people like music.' },
    { wordId: 'on the other hand', english: 'On the other hand, I can wait.' },

    // Level 16 · society, conditions, and contrast
    { wordId: 'advantage', english: 'This plan has an advantage.' },
    { wordId: 'disadvantage', english: 'Every choice has a disadvantage.' },
    { wordId: 'benefit', english: 'Exercise has a benefit.' },
    { wordId: 'quality', english: 'This product has good quality.' },
    { wordId: 'importance', english: 'I know the importance of rest.' },
    { wordId: 'possibility', english: 'There is a possibility of rain.' },
    { wordId: 'reality', english: 'This story is based on reality.' },
    { wordId: 'issue', english: 'We discuss this issue.' },
    { wordId: 'solution', english: 'We found a solution.' },
    { wordId: 'measure', english: 'We measure the distance.' },
    { wordId: 'policy', english: 'This policy protects people.' },
    { wordId: 'responsibility', english: 'This is my responsibility.' },
    { wordId: 'right_lv16', english: 'You have the right to choose.' },
    { wordId: 'duty', english: 'It is my duty to help.' },
    { wordId: 'freedom', english: 'Everyone needs freedom.' },
    { wordId: 'justice', english: 'We hope for justice.' },
    { wordId: 'peace', english: 'We all want peace.' },
    { wordId: 'war', english: 'War causes great pain.' },
    { wordId: 'crime', english: 'The law can prevent crime.' },
    { wordId: 'pollution', english: 'Pollution harms the sea.' },
    { wordId: 'waste', english: 'Please reduce food waste.' },
    { wordId: 'climate', english: 'The climate is changing.' },
    { wordId: 'temperature', english: 'The temperature is low.' },
    { wordId: 'atmosphere', english: 'The atmosphere is calm.' },
    { wordId: 'disaster', english: 'The flood was a disaster.' },
    { wordId: 'earthquake', english: 'An earthquake can damage homes.' },
    { wordId: 'flood', english: 'Heavy rain can cause a flood.' },
    { wordId: 'damage', english: 'The storm caused damage.' },
    { wordId: 'unique', english: 'This flower is unique.' },
    { wordId: 'rare', english: 'This bird is rare.' },
    { wordId: 'ordinary', english: 'This is an ordinary day.' },
    { wordId: 'typical', english: 'This is a typical example.' },
    { wordId: 'obvious', english: 'The answer is obvious.' },
    { wordId: 'clear', english: 'The sky is clear.' },
    { wordId: 'visible', english: 'The moon is visible.' },
    { wordId: 'complex', english: 'This problem is complex.' },
    { wordId: 'efficient', english: 'This method is efficient.' },
    { wordId: 'practical', english: 'This is a practical tool.' },
    { wordId: 'suitable', english: 'This seat is suitable.' },
    { wordId: 'convenient', english: 'This map is convenient.' },
    { wordId: 'comfortable', english: 'This chair is comfortable.' },
    { wordId: 'accurate', english: 'This answer is accurate.' },
    { wordId: 'reliable', english: 'This machine is reliable.' },
    { wordId: 'valuable', english: 'This experience is valuable.' },
    { wordId: 'essential', english: 'Water is essential for life.' },
    { wordId: 'consequently', english: 'It rained; consequently, we stayed home.' },
    { wordId: 'accordingly', english: 'The plan changed; we acted accordingly.' },
    { wordId: 'nevertheless', english: 'It was hard; nevertheless, I tried.' },
    { wordId: 'meanwhile', english: 'I read; meanwhile, she slept.' },
    { wordId: 'hence', english: 'It was late; hence, we went home.' },
    { wordId: 'nonetheless', english: 'It was cold; nonetheless, we played.' },
    { wordId: 'regardless of', english: 'Regardless of rain, we play.' },
    { wordId: 'in spite of', english: 'In spite of rain, we walk.' },
    { wordId: 'due to', english: 'The game stopped due to rain.' },
    { wordId: 'owing to', english: 'Owing to rain, the game stopped.' },
    { wordId: 'as a result', english: 'As a result, we stayed home.' },
    { wordId: 'in terms of', english: 'In terms of time, this is short.' },
    { wordId: 'with regard to', english: 'With regard to safety, we wait.' },
    { wordId: 'in contrast', english: 'In contrast, this road is wide.' },

    // Level 17 · society, learning, and degree
    { wordId: 'nation', english: 'Japan is an island nation.' },
    { wordId: 'border', english: 'The river forms a border.' },
    { wordId: 'citizen', english: 'Every citizen can vote.' },
    { wordId: 'population', english: 'The city has a large population.' },
    { wordId: 'economy', english: 'The economy is changing.' },
    { wordId: 'industry', english: 'This industry makes useful tools.' },
    { wordId: 'business', english: 'Her family runs a business.' },
    { wordId: 'trade', english: 'Trade connects many countries.' },
    { wordId: 'market', english: 'We buy fruit at the market.' },
    { wordId: 'product', english: 'This product is useful.' },
    { wordId: 'profit', english: 'The company made a profit.' },
    { wordId: 'cost', english: 'The cost is high.' },
    { wordId: 'investment', english: 'Education is a good investment.' },
    { wordId: 'competition', english: 'Healthy competition can help.' },
    { wordId: 'company', english: 'This company makes books.' },
    { wordId: 'customer', english: 'The customer chose a book.' },
    { wordId: 'consumer', english: 'A consumer buys a product.' },
    { wordId: 'education', english: 'Education opens new doors.' },
    { wordId: 'knowledge', english: 'Knowledge helps us learn.' },
    { wordId: 'skill', english: 'Practice builds a skill.' },
    { wordId: 'ability', english: 'She has the ability to learn.' },
    { wordId: 'intelligence', english: 'Intelligence helps solve problems.' },
    { wordId: 'talent', english: 'The singer has great talent.' },
    { wordId: 'degree', english: 'She has a science degree.' },
    { wordId: 'disease', english: 'Medicine can treat disease.' },
    { wordId: 'medicine', english: 'The doctor gives medicine.' },
    { wordId: 'treatment', english: 'This treatment helps patients.' },
    { wordId: 'exercise', english: 'Daily exercise keeps us healthy.' },
    { wordId: 'economic', english: 'This is an economic problem.' },
    { wordId: 'political', english: 'This is a political issue.' },
    { wordId: 'cultural', english: 'We enjoy cultural events.' },
    { wordId: 'environmental', english: 'We need environmental action.' },
    { wordId: 'traditional', english: 'This is a traditional song.' },
    { wordId: 'scientific', english: 'This is a scientific experiment.' },
    { wordId: 'technical', english: 'I need technical support.' },
    { wordId: 'industrial', english: 'This is an industrial city.' },
    { wordId: 'international', english: 'We share an international goal.' },
    { wordId: 'foreign', english: 'I study a foreign language.' },
    { wordId: 'significant', english: 'This is a significant change.' },
    { wordId: 'considerable', english: 'This needs considerable effort.' },
    { wordId: 'remarkable', english: 'This is a remarkable result.' },
    { wordId: 'slight', english: 'There is a slight change.' },
    { wordId: 'gradual', english: 'Progress can be gradual.' },
    { wordId: 'rapid', english: 'The bird makes a rapid turn.' },
    { wordId: 'sudden', english: 'A sudden rain stopped play.' },
    { wordId: 'steady', english: 'We make steady progress.' },
    { wordId: 'significantly', english: 'The price increased significantly.' },
    { wordId: 'considerably', english: 'The cost decreased considerably.' },
    { wordId: 'slightly', english: 'The color changed slightly.' },
    { wordId: 'gradually', english: 'The plant grows gradually.' },
    { wordId: 'rapidly', english: 'The river rises rapidly.' },
    { wordId: 'dramatically', english: 'The weather changed dramatically.' },
    { wordId: 'substantially', english: 'The plan improved substantially.' },
    { wordId: 'severely', english: 'The storm damaged homes severely.' },
    { wordId: 'in order to', english: 'I study in order to learn.' },
    { wordId: 'so as to', english: 'We hurry so as to arrive.' },
    { wordId: 'as well as', english: 'I read as well as write.' },
    { wordId: 'rather than', english: 'I walk rather than run.' },
    { wordId: 'other than', english: 'Everyone other than me is ready.' },
    { wordId: 'as long as', english: 'As long as it is safe, play.' },

    // Level 18 · health, communication, and manner
    { wordId: 'diet', english: 'A healthy diet helps.' },
    { wordId: 'habit', english: 'Reading is a good habit.' },
    { wordId: 'symptom', english: 'A cough is a common symptom.' },
    { wordId: 'recovery', english: 'Rest helps my recovery.' },
    { wordId: 'patient', english: 'The patient needs rest.' },
    { wordId: 'speech', english: 'Her speech was clear.' },
    { wordId: 'message', english: 'I sent a message.' },
    { wordId: 'signal', english: 'The light is a signal.' },
    { wordId: 'advice', english: 'My teacher gives good advice.' },
    { wordId: 'instruction', english: 'Please follow the instruction.' },
    { wordId: 'direction', english: 'The map shows the direction.' },
    { wordId: 'explanation', english: 'Your explanation is clear.' },
    { wordId: 'description', english: 'I read the description.' },
    { wordId: 'beginning', english: 'This is the beginning.' },
    { wordId: 'ending', english: 'The story has a happy ending.' },
    { wordId: 'origin', english: 'I know the origin.' },
    { wordId: 'development', english: 'The project needs development.' },
    { wordId: 'evolution', english: 'Evolution takes a long time.' },
    { wordId: 'revolution', english: 'The revolution changed history.' },
    { wordId: 'trend', english: 'This is a new trend.' },
    { wordId: 'pattern', english: 'I see a pattern.' },
    { wordId: 'structure', english: 'The bridge has a strong structure.' },
    { wordId: 'shape', english: 'This shape is round.' },
    { wordId: 'material', english: 'Wood is a natural material.' },
    { wordId: 'equipment', english: 'The team needs new equipment.' },
    { wordId: 'device', english: 'This device is useful.' },
    { wordId: 'tool', english: 'This tool is helpful.' },
    { wordId: 'machine', english: 'The machine works well.' },
    { wordId: 'vehicle', english: 'This vehicle can carry people.' },
    { wordId: 'anxious', english: 'I feel anxious today.' },
    { wordId: 'nervous', english: 'I feel nervous now.' },
    { wordId: 'embarrassed', english: 'I feel embarrassed today.' },
    { wordId: 'grateful', english: 'I am grateful for your help.' },
    { wordId: 'proud', english: 'I am proud of my work.' },
    { wordId: 'ashamed', english: 'He feels ashamed of the mistake.' },
    { wordId: 'curious', english: 'The child is curious.' },
    { wordId: 'eager', english: 'I am eager to learn.' },
    { wordId: 'willing', english: 'I am willing to help.' },
    { wordId: 'reluctant', english: 'He is reluctant to go.' },
    { wordId: 'temporary', english: 'This is a temporary change.' },
    { wordId: 'permanent', english: 'This is a permanent change.' },
    { wordId: 'constant', english: 'The machine makes a constant sound.' },
    { wordId: 'regular', english: 'We have regular practice.' },
    { wordId: 'frequent', english: 'Frequent rain fills the river.' },
    { wordId: 'occasional', english: 'We have occasional rain.' },
    { wordId: 'annual', english: 'We have an annual festival.' },
    { wordId: 'immediate', english: 'We need immediate help.' },
    { wordId: 'severe', english: 'The storm caused severe damage.' },
    { wordId: 'mild', english: 'The weather is mild today.' },
    { wordId: 'properly_lv18', english: 'Please use the tool properly.' },
    { wordId: 'effectively', english: 'We can work effectively together.' },
    { wordId: 'efficiently', english: 'The machine works efficiently.' },
    { wordId: 'naturally', english: 'The flower grows naturally.' },
    { wordId: 'automatically', english: 'The door closes automatically.' },
    { wordId: 'deliberately', english: 'I deliberately chose this path.' },
    { wordId: 'accidentally', english: 'I accidentally dropped the cup.' },
    { wordId: 'voluntarily', english: 'She voluntarily joined the team.' },
    { wordId: 'on behalf of', english: 'I speak on behalf of the team.' },
    { wordId: 'in case of', english: 'In case of rain, stay inside.' },
    { wordId: 'by means of', english: 'We learn by means of practice.' },

    // Level 19 · analysis, cooperation, and evidence
    { wordId: 'analyze', english: 'We analyze the problem.' },
    { wordId: 'examine', english: 'I examine the picture.' },
    { wordId: 'investigate', english: 'They investigate the cause.' },
    { wordId: 'explore', english: 'We explore the forest.' },
    { wordId: 'evaluate', english: 'We evaluate the result.' },
    { wordId: 'judge', english: 'Do not judge too quickly.' },
    { wordId: 'estimate', english: 'I estimate the time.' },
    { wordId: 'calculate', english: 'We calculate the total.' },
    { wordId: 'design', english: 'We design a new house.' },
    { wordId: 'invent', english: 'People invent useful tools.' },
    { wordId: 'discover', english: 'We discover a new path.' },
    { wordId: 'establish', english: 'They establish a new rule.' },
    { wordId: 'organize', english: 'We organize the event.' },
    { wordId: 'arrange', english: 'I arrange the chairs.' },
    { wordId: 'construct', english: 'They construct a bridge.' },
    { wordId: 'demonstrate', english: 'The teacher demonstrates the method.' },
    { wordId: 'illustrate', english: 'This picture illustrates the idea.' },
    { wordId: 'indicate', english: 'The sign indicates the way.' },
    { wordId: 'imply', english: 'His words imply a problem.' },
    { wordId: 'refer', english: 'I refer to the map.' },
    { wordId: 'define', english: 'We define the new word.' },
    { wordId: 'clarify', english: 'Please clarify the question.' },
    { wordId: 'transform', english: 'Rain can transform the land.' },
    { wordId: 'convert', english: 'We convert water into ice.' },
    { wordId: 'replace', english: 'Please replace the old pen.' },
    { wordId: 'restore', english: 'We restore the old house.' },
    { wordId: 'recover', english: 'I recover after some rest.' },
    { wordId: 'survive', english: 'Plants can survive without water.' },
    { wordId: 'destroy', english: 'Storms can destroy houses.' },
    { wordId: 'participate', english: 'We participate in the event.' },
    { wordId: 'contribute', english: 'Everyone can contribute ideas.' },
    { wordId: 'cooperate', english: 'We cooperate as a team.' },
    { wordId: 'compete', english: 'The teams compete fairly.' },
    { wordId: 'negotiate', english: 'They negotiate a fair price.' },
    { wordId: 'communicate', english: 'We communicate with words.' },
    { wordId: 'limit', english: 'We limit our screen time.' },
    { wordId: 'restrict', english: 'Rules restrict unsafe actions.' },
    { wordId: 'regulate', english: 'Rules regulate traffic.' },
    { wordId: 'preserve', english: 'We preserve old stories.' },
    { wordId: 'conserve', english: 'We conserve water.' },
    { wordId: 'secure', english: 'Please secure the door.' },
    { wordId: 'ensure', english: 'We ensure the door is closed.' },
    { wordId: 'appreciate', english: 'I appreciate your help.' },
    { wordId: 'respect', english: 'We respect every person.' },
    { wordId: 'admire', english: 'I admire the brave girl.' },
    { wordId: 'blame', english: 'Do not blame your friend.' },
    { wordId: 'criticize', english: 'We can criticize the plan kindly.' },
    { wordId: 'complain', english: 'Please do not complain.' },
    { wordId: 'apologize', english: 'I apologize to my friend.' },
    { wordId: 'forgive', english: 'I forgive your mistake.' },
    { wordId: 'standard', english: 'This is the standard rule.' },
    { wordId: 'principle', english: 'This principle guides us.' },
    { wordId: 'theory', english: 'This theory explains the result.' },
    { wordId: 'concept', english: 'I understand the concept.' },
    { wordId: 'aspect', english: 'This aspect is important.' },
    { wordId: 'feature', english: 'This feature is useful.' },
    { wordId: 'factor', english: 'Time is an important factor.' },
    { wordId: 'element', english: 'Water is an important element.' },
    { wordId: 'circumstance', english: 'Every circumstance is different.' },
    { wordId: 'evidence', english: 'We need clear evidence.' },

    // Level 20 · precision, possibility, and result
    { wordId: 'identify', english: 'I can identify the bird.' },
    { wordId: 'locate', english: 'We locate the lost key.' },
    { wordId: 'obtain', english: 'I obtain a new book.' },
    { wordId: 'acquire', english: 'We acquire new skills.' },
    { wordId: 'possess', english: 'I possess a useful tool.' },
    { wordId: 'distribute', english: 'We distribute food fairly.' },
    { wordId: 'deliver', english: 'They deliver the package.' },
    { wordId: 'release', english: 'We release the bird.' },
    { wordId: 'publish', english: 'They publish a new book.' },
    { wordId: 'reveal', english: 'The picture reveals the truth.' },
    { wordId: 'expose', english: 'The light can expose dust.' },
    { wordId: 'perceive', english: 'We perceive a small change.' },
    { wordId: 'observe', english: 'We observe the bird.' },
    { wordId: 'conclude', english: 'We conclude the lesson.' },
    { wordId: 'confirm', english: 'Please confirm the answer.' },
    { wordId: 'guarantee', english: 'Nothing can guarantee success.' },
    { wordId: 'eliminate', english: 'We eliminate the problem.' },
    { wordId: 'ignore', english: 'Please do not ignore the rule.' },
    { wordId: 'consist', english: 'The team consists of five people.' },
    { wordId: 'belong', english: 'This book belongs to me.' },
    { wordId: 'adequate', english: 'This room is adequate.' },
    { wordId: 'sufficient', english: 'We have sufficient time.' },
    { wordId: 'excessive', english: 'Excessive rain can cause floods.' },
    { wordId: 'numerous', english: 'Numerous stars fill the sky.' },
    { wordId: 'vast', english: 'The ocean is vast.' },
    { wordId: 'limited', english: 'We have limited time.' },
    { wordId: 'independent', english: 'The child is independent.' },
    { wordId: 'mutual', english: 'We have mutual respect.' },
    { wordId: 'alternative', english: 'This is an alternative plan.' },
    { wordId: 'potential', english: 'This idea has potential.' },
    { wordId: 'latter', english: 'I prefer the latter choice.' },
    { wordId: 'precise', english: 'This answer is precise.' },
    { wordId: 'religious', english: 'This is a religious festival.' },
    { wordId: 'invisible', english: 'The wind is invisible.' },
    { wordId: 'apparent', english: 'The answer is apparent.' },
    { wordId: 'presumably', english: 'Presumably, the bus is late.' },
    { wordId: 'possibly', english: 'It will possibly rain.' },
    { wordId: 'unlikely', english: 'Rain is unlikely today.' },
    { wordId: 'necessarily', english: 'It is not necessarily true.' },
    { wordId: 'inevitably', english: 'Change will inevitably come.' },
    { wordId: 'undoubtedly', english: 'She is undoubtedly kind.' },
    { wordId: 'evidently', english: 'The answer is evidently right.' },
    { wordId: 'whereas', english: 'I like tea, whereas she likes juice.' },
    { wordId: 'thereby', english: 'We practice, thereby improving skills.' },
    { wordId: 'as far as', english: 'As far as possible, we wait.' },
    { wordId: 'at most', english: 'Take at most two books.' },
    { wordId: 'yearly', english: 'We have a yearly festival.' },
];

export const ENGLISH_EXAMPLE_SENTENCES: readonly EnglishExampleSentence[] = examples;

/**
 * Returns the fixed example for a vocabulary learning item.
 *
 * The lookup stays ID-based so saved problems keep the same behavior even if
 * the visible word is customized or legacy data is used.
 */
export function getEnglishExampleSentence(wordId: string): string | undefined {
    return ENGLISH_EXAMPLE_SENTENCES.find(sentence => sentence.wordId === wordId)?.english;
}
